// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: dish_service.proto

package restaurant_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishID        uint32                 `protobuf:"varint,1,opt,name=dishID,proto3" json:"dishID,omitempty"`
	DishName      string                 `protobuf:"bytes,2,opt,name=dishName,proto3" json:"dishName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dish) Reset() {
	*x = Dish{}
	mi := &file_dish_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{0}
}

func (x *Dish) GetDishID() uint32 {
	if x != nil {
		return x.DishID
	}
	return 0
}

func (x *Dish) GetDishName() string {
	if x != nil {
		return x.DishName
	}
	return ""
}

type GetAllDishesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*Dish                `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDishesResp) Reset() {
	*x = GetAllDishesResp{}
	mi := &file_dish_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDishesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDishesResp) ProtoMessage() {}

func (x *GetAllDishesResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDishesResp.ProtoReflect.Descriptor instead.
func (*GetAllDishesResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllDishesResp) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

func (x *GetAllDishesResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_dish_service_proto protoreflect.FileDescriptor

const file_dish_service_proto_rawDesc = "" +
	"\n" +
	"\x12dish_service.proto\x12\x0erestaurant_rpc\x1a\x1bgoogle/protobuf/empty.proto\":\n" +
	"\x04Dish\x12\x16\n" +
	"\x06dishID\x18\x01 \x01(\rR\x06dishID\x12\x1a\n" +
	"\bdishName\x18\x02 \x01(\tR\bdishName\"V\n" +
	"\x10GetAllDishesResp\x12,\n" +
	"\x06dishes\x18\x01 \x03(\v2\x14.restaurant_rpc.DishR\x06dishes\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2Y\n" +
	"\vDishService\x12J\n" +
	"\fGetAllDishes\x12\x16.google.protobuf.Empty\x1a .restaurant_rpc.GetAllDishesResp\"\x00B\x11Z\x0frestaurant_rpc/b\x06proto3"

var (
	file_dish_service_proto_rawDescOnce sync.Once
	file_dish_service_proto_rawDescData []byte
)

func file_dish_service_proto_rawDescGZIP() []byte {
	file_dish_service_proto_rawDescOnce.Do(func() {
		file_dish_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dish_service_proto_rawDesc), len(file_dish_service_proto_rawDesc)))
	})
	return file_dish_service_proto_rawDescData
}

var file_dish_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dish_service_proto_goTypes = []any{
	(*Dish)(nil),             // 0: restaurant_rpc.Dish
	(*GetAllDishesResp)(nil), // 1: restaurant_rpc.GetAllDishesResp
	(*emptypb.Empty)(nil),    // 2: google.protobuf.Empty
}
var file_dish_service_proto_depIdxs = []int32{
	0, // 0: restaurant_rpc.GetAllDishesResp.dishes:type_name -> restaurant_rpc.Dish
	2, // 1: restaurant_rpc.DishService.GetAllDishes:input_type -> google.protobuf.Empty
	1, // 2: restaurant_rpc.DishService.GetAllDishes:output_type -> restaurant_rpc.GetAllDishesResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dish_service_proto_init() }
func file_dish_service_proto_init() {
	if File_dish_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dish_service_proto_rawDesc), len(file_dish_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dish_service_proto_goTypes,
		DependencyIndexes: file_dish_service_proto_depIdxs,
		MessageInfos:      file_dish_service_proto_msgTypes,
	}.Build()
	File_dish_service_proto = out.File
	file_dish_service_proto_goTypes = nil
	file_dish_service_proto_depIdxs = nil
}
