// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: basic_service.proto

package restaurant_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRole int32

const (
	LoginRole_LOGIN_ROLE_UNKNOWN  LoginRole = 0 // 未知登录角色
	LoginRole_LOGIN_ROLE_CUSTOMER LoginRole = 1 // 顾客角色
	LoginRole_LOGIN_ROLE_EMPLOYEE LoginRole = 2 // 雇员角色
)

// Enum value maps for LoginRole.
var (
	LoginRole_name = map[int32]string{
		0: "LOGIN_ROLE_UNKNOWN",
		1: "LOGIN_ROLE_CUSTOMER",
		2: "LOGIN_ROLE_EMPLOYEE",
	}
	LoginRole_value = map[string]int32{
		"LOGIN_ROLE_UNKNOWN":  0,
		"LOGIN_ROLE_CUSTOMER": 1,
		"LOGIN_ROLE_EMPLOYEE": 2,
	}
)

func (x LoginRole) Enum() *LoginRole {
	p := new(LoginRole)
	*p = x
	return p
}

func (x LoginRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginRole) Descriptor() protoreflect.EnumDescriptor {
	return file_basic_service_proto_enumTypes[0].Descriptor()
}

func (LoginRole) Type() protoreflect.EnumType {
	return &file_basic_service_proto_enumTypes[0]
}

func (x LoginRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginRole.Descriptor instead.
func (LoginRole) EnumDescriptor() ([]byte, []int) {
	return file_basic_service_proto_rawDescGZIP(), []int{0}
}

type EmployeeRole int32

const (
	EmployeeRole_ROLE_UNKNOWN EmployeeRole = 0
	EmployeeRole_ROLE_ADMIN   EmployeeRole = 1
	EmployeeRole_ROLE_MANAGER EmployeeRole = 2
)

// Enum value maps for EmployeeRole.
var (
	EmployeeRole_name = map[int32]string{
		0: "ROLE_UNKNOWN",
		1: "ROLE_ADMIN",
		2: "ROLE_MANAGER",
	}
	EmployeeRole_value = map[string]int32{
		"ROLE_UNKNOWN": 0,
		"ROLE_ADMIN":   1,
		"ROLE_MANAGER": 2,
	}
)

func (x EmployeeRole) Enum() *EmployeeRole {
	p := new(EmployeeRole)
	*p = x
	return p
}

func (x EmployeeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmployeeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_basic_service_proto_enumTypes[1].Descriptor()
}

func (EmployeeRole) Type() protoreflect.EnumType {
	return &file_basic_service_proto_enumTypes[1]
}

func (x EmployeeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmployeeRole.Descriptor instead.
func (EmployeeRole) EnumDescriptor() ([]byte, []int) {
	return file_basic_service_proto_rawDescGZIP(), []int{1}
}

type RespStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespStatus) Reset() {
	*x = RespStatus{}
	mi := &file_basic_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespStatus) ProtoMessage() {}

func (x *RespStatus) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespStatus.ProtoReflect.Descriptor instead.
func (*RespStatus) Descriptor() ([]byte, []int) {
	return file_basic_service_proto_rawDescGZIP(), []int{0}
}

func (x *RespStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RespStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoginReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UsernameOrPhone string                 `protobuf:"bytes,1,opt,name=usernameOrPhone,proto3" json:"usernameOrPhone,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role            LoginRole              `protobuf:"varint,3,opt,name=role,proto3,enum=restaurant_rpc.LoginRole" json:"role,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_basic_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_basic_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReq) GetUsernameOrPhone() string {
	if x != nil {
		return x.UsernameOrPhone
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetRole() LoginRole {
	if x != nil {
		return x.Role
	}
	return LoginRole_LOGIN_ROLE_UNKNOWN
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	Status        *RespStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	UserID        uint32                 `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	Role          LoginRole              `protobuf:"varint,5,opt,name=role,proto3,enum=restaurant_rpc.LoginRole" json:"role,omitempty"`
	EmployeeRole  EmployeeRole           `protobuf:"varint,6,opt,name=employeeRole,proto3,enum=restaurant_rpc.EmployeeRole" json:"employeeRole,omitempty"` // 仅雇员时该字段有值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_basic_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_basic_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResp) GetStatus() *RespStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *LoginResp) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *LoginResp) GetRole() LoginRole {
	if x != nil {
		return x.Role
	}
	return LoginRole_LOGIN_ROLE_UNKNOWN
}

func (x *LoginResp) GetEmployeeRole() EmployeeRole {
	if x != nil {
		return x.EmployeeRole
	}
	return EmployeeRole_ROLE_UNKNOWN
}

type RegisterReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Username         string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password         string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	RepeatedPassword string                 `protobuf:"bytes,3,opt,name=repeatedPassword,proto3" json:"repeatedPassword,omitempty"`
	Phone            string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_basic_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_basic_service_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetRepeatedPassword() string {
	if x != nil {
		return x.RepeatedPassword
	}
	return ""
}

func (x *RegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	Status        *RespStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	UserID        uint32                 `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	Role          LoginRole              `protobuf:"varint,5,opt,name=role,proto3,enum=restaurant_rpc.LoginRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_basic_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_basic_service_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RegisterResp) GetStatus() *RespStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RegisterResp) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RegisterResp) GetRole() LoginRole {
	if x != nil {
		return x.Role
	}
	return LoginRole_LOGIN_ROLE_UNKNOWN
}

type RefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_basic_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_basic_service_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResp) Reset() {
	*x = RefreshTokenResp{}
	mi := &file_basic_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResp) ProtoMessage() {}

func (x *RefreshTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResp.ProtoReflect.Descriptor instead.
func (*RefreshTokenResp) Descriptor() ([]byte, []int) {
	return file_basic_service_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type CanRegisterAdminResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CanRegisterAdmin bool                   `protobuf:"varint,1,opt,name=canRegisterAdmin,proto3" json:"canRegisterAdmin,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CanRegisterAdminResp) Reset() {
	*x = CanRegisterAdminResp{}
	mi := &file_basic_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanRegisterAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanRegisterAdminResp) ProtoMessage() {}

func (x *CanRegisterAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanRegisterAdminResp.ProtoReflect.Descriptor instead.
func (*CanRegisterAdminResp) Descriptor() ([]byte, []int) {
	return file_basic_service_proto_rawDescGZIP(), []int{7}
}

func (x *CanRegisterAdminResp) GetCanRegisterAdmin() bool {
	if x != nil {
		return x.CanRegisterAdmin
	}
	return false
}

type RegisterAdminReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Phone            string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password         string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	RepeatedPassword string                 `protobuf:"bytes,3,opt,name=repeatedPassword,proto3" json:"repeatedPassword,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterAdminReq) Reset() {
	*x = RegisterAdminReq{}
	mi := &file_basic_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAdminReq) ProtoMessage() {}

func (x *RegisterAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAdminReq.ProtoReflect.Descriptor instead.
func (*RegisterAdminReq) Descriptor() ([]byte, []int) {
	return file_basic_service_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterAdminReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterAdminReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterAdminReq) GetRepeatedPassword() string {
	if x != nil {
		return x.RepeatedPassword
	}
	return ""
}

type RegisterAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	UserID        uint32                 `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAdminResp) Reset() {
	*x = RegisterAdminResp{}
	mi := &file_basic_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAdminResp) ProtoMessage() {}

func (x *RegisterAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAdminResp.ProtoReflect.Descriptor instead.
func (*RegisterAdminResp) Descriptor() ([]byte, []int) {
	return file_basic_service_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterAdminResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterAdminResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RegisterAdminResp) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

var File_basic_service_proto protoreflect.FileDescriptor

const file_basic_service_proto_rawDesc = "" +
	"\n" +
	"\x13basic_service.proto\x12\x0erestaurant_rpc\x1a\x1bgoogle/protobuf/empty.proto\":\n" +
	"\n" +
	"RespStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x7f\n" +
	"\bLoginReq\x12(\n" +
	"\x0fusernameOrPhone\x18\x01 \x01(\tR\x0fusernameOrPhone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12-\n" +
	"\x04role\x18\x03 \x01(\x0e2\x19.restaurant_rpc.LoginRoleR\x04role\"\x8e\x02\n" +
	"\tLoginResp\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x122\n" +
	"\x06status\x18\x03 \x01(\v2\x1a.restaurant_rpc.RespStatusR\x06status\x12\x16\n" +
	"\x06userID\x18\x04 \x01(\rR\x06userID\x12-\n" +
	"\x04role\x18\x05 \x01(\x0e2\x19.restaurant_rpc.LoginRoleR\x04role\x12@\n" +
	"\femployeeRole\x18\x06 \x01(\x0e2\x1c.restaurant_rpc.EmployeeRoleR\femployeeRole\"\x87\x01\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12*\n" +
	"\x10repeatedPassword\x18\x03 \x01(\tR\x10repeatedPassword\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"\xcf\x01\n" +
	"\fRegisterResp\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x122\n" +
	"\x06status\x18\x03 \x01(\v2\x1a.restaurant_rpc.RespStatusR\x06status\x12\x16\n" +
	"\x06userID\x18\x04 \x01(\rR\x06userID\x12-\n" +
	"\x04role\x18\x05 \x01(\x0e2\x19.restaurant_rpc.LoginRoleR\x04role\"5\n" +
	"\x0fRefreshTokenReq\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\tR\frefreshToken\"X\n" +
	"\x10RefreshTokenResp\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\"B\n" +
	"\x14CanRegisterAdminResp\x12*\n" +
	"\x10canRegisterAdmin\x18\x01 \x01(\bR\x10canRegisterAdmin\"p\n" +
	"\x10RegisterAdminReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12*\n" +
	"\x10repeatedPassword\x18\x03 \x01(\tR\x10repeatedPassword\"q\n" +
	"\x11RegisterAdminResp\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\rR\x06userID*U\n" +
	"\tLoginRole\x12\x16\n" +
	"\x12LOGIN_ROLE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13LOGIN_ROLE_CUSTOMER\x10\x01\x12\x17\n" +
	"\x13LOGIN_ROLE_EMPLOYEE\x10\x02*B\n" +
	"\fEmployeeRole\x12\x10\n" +
	"\fROLE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x01\x12\x10\n" +
	"\fROLE_MANAGER\x10\x022\x97\x03\n" +
	"\vAuthService\x12>\n" +
	"\x05Login\x12\x18.restaurant_rpc.LoginReq\x1a\x19.restaurant_rpc.LoginResp\"\x00\x12G\n" +
	"\bRegister\x12\x1b.restaurant_rpc.RegisterReq\x1a\x1c.restaurant_rpc.RegisterResp\"\x00\x12S\n" +
	"\fRefreshToken\x12\x1f.restaurant_rpc.RefreshTokenReq\x1a .restaurant_rpc.RefreshTokenResp\"\x00\x12R\n" +
	"\x10CanRegisterAdmin\x12\x16.google.protobuf.Empty\x1a$.restaurant_rpc.CanRegisterAdminResp\"\x00\x12V\n" +
	"\rRegisterAdmin\x12 .restaurant_rpc.RegisterAdminReq\x1a!.restaurant_rpc.RegisterAdminResp\"\x00B'Z%restaurant_backend/rpc;restaurant_rpcb\x06proto3"

var (
	file_basic_service_proto_rawDescOnce sync.Once
	file_basic_service_proto_rawDescData []byte
)

func file_basic_service_proto_rawDescGZIP() []byte {
	file_basic_service_proto_rawDescOnce.Do(func() {
		file_basic_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basic_service_proto_rawDesc), len(file_basic_service_proto_rawDesc)))
	})
	return file_basic_service_proto_rawDescData
}

var file_basic_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_basic_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_basic_service_proto_goTypes = []any{
	(LoginRole)(0),               // 0: restaurant_rpc.LoginRole
	(EmployeeRole)(0),            // 1: restaurant_rpc.EmployeeRole
	(*RespStatus)(nil),           // 2: restaurant_rpc.RespStatus
	(*LoginReq)(nil),             // 3: restaurant_rpc.LoginReq
	(*LoginResp)(nil),            // 4: restaurant_rpc.LoginResp
	(*RegisterReq)(nil),          // 5: restaurant_rpc.RegisterReq
	(*RegisterResp)(nil),         // 6: restaurant_rpc.RegisterResp
	(*RefreshTokenReq)(nil),      // 7: restaurant_rpc.RefreshTokenReq
	(*RefreshTokenResp)(nil),     // 8: restaurant_rpc.RefreshTokenResp
	(*CanRegisterAdminResp)(nil), // 9: restaurant_rpc.CanRegisterAdminResp
	(*RegisterAdminReq)(nil),     // 10: restaurant_rpc.RegisterAdminReq
	(*RegisterAdminResp)(nil),    // 11: restaurant_rpc.RegisterAdminResp
	(*emptypb.Empty)(nil),        // 12: google.protobuf.Empty
}
var file_basic_service_proto_depIdxs = []int32{
	0,  // 0: restaurant_rpc.LoginReq.role:type_name -> restaurant_rpc.LoginRole
	2,  // 1: restaurant_rpc.LoginResp.status:type_name -> restaurant_rpc.RespStatus
	0,  // 2: restaurant_rpc.LoginResp.role:type_name -> restaurant_rpc.LoginRole
	1,  // 3: restaurant_rpc.LoginResp.employeeRole:type_name -> restaurant_rpc.EmployeeRole
	2,  // 4: restaurant_rpc.RegisterResp.status:type_name -> restaurant_rpc.RespStatus
	0,  // 5: restaurant_rpc.RegisterResp.role:type_name -> restaurant_rpc.LoginRole
	3,  // 6: restaurant_rpc.AuthService.Login:input_type -> restaurant_rpc.LoginReq
	5,  // 7: restaurant_rpc.AuthService.Register:input_type -> restaurant_rpc.RegisterReq
	7,  // 8: restaurant_rpc.AuthService.RefreshToken:input_type -> restaurant_rpc.RefreshTokenReq
	12, // 9: restaurant_rpc.AuthService.CanRegisterAdmin:input_type -> google.protobuf.Empty
	10, // 10: restaurant_rpc.AuthService.RegisterAdmin:input_type -> restaurant_rpc.RegisterAdminReq
	4,  // 11: restaurant_rpc.AuthService.Login:output_type -> restaurant_rpc.LoginResp
	6,  // 12: restaurant_rpc.AuthService.Register:output_type -> restaurant_rpc.RegisterResp
	8,  // 13: restaurant_rpc.AuthService.RefreshToken:output_type -> restaurant_rpc.RefreshTokenResp
	9,  // 14: restaurant_rpc.AuthService.CanRegisterAdmin:output_type -> restaurant_rpc.CanRegisterAdminResp
	11, // 15: restaurant_rpc.AuthService.RegisterAdmin:output_type -> restaurant_rpc.RegisterAdminResp
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_basic_service_proto_init() }
func file_basic_service_proto_init() {
	if File_basic_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basic_service_proto_rawDesc), len(file_basic_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_basic_service_proto_goTypes,
		DependencyIndexes: file_basic_service_proto_depIdxs,
		EnumInfos:         file_basic_service_proto_enumTypes,
		MessageInfos:      file_basic_service_proto_msgTypes,
	}.Build()
	File_basic_service_proto = out.File
	file_basic_service_proto_goTypes = nil
	file_basic_service_proto_depIdxs = nil
}
