// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: cost_service.proto

package restaurant_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CostId        uint32                 `protobuf:"varint,1,opt,name=costId,proto3" json:"costId,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	CostType      CostType               `protobuf:"varint,3,opt,name=costType,proto3,enum=restaurant_rpc.CostType" json:"costType,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostInfo) Reset() {
	*x = CostInfo{}
	mi := &file_cost_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostInfo) ProtoMessage() {}

func (x *CostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cost_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostInfo.ProtoReflect.Descriptor instead.
func (*CostInfo) Descriptor() ([]byte, []int) {
	return file_cost_service_proto_rawDescGZIP(), []int{0}
}

func (x *CostInfo) GetCostId() uint32 {
	if x != nil {
		return x.CostId
	}
	return 0
}

func (x *CostInfo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CostInfo) GetCostType() CostType {
	if x != nil {
		return x.CostType
	}
	return CostType_COST_TYPE_UNKNOWN
}

func (x *CostInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetAllCostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CostInfoList  []*CostInfo            `protobuf:"bytes,1,rep,name=costInfoList,proto3" json:"costInfoList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCostResp) Reset() {
	*x = GetAllCostResp{}
	mi := &file_cost_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCostResp) ProtoMessage() {}

func (x *GetAllCostResp) ProtoReflect() protoreflect.Message {
	mi := &file_cost_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCostResp.ProtoReflect.Descriptor instead.
func (*GetAllCostResp) Descriptor() ([]byte, []int) {
	return file_cost_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllCostResp) GetCostInfoList() []*CostInfo {
	if x != nil {
		return x.CostInfoList
	}
	return nil
}

var File_cost_service_proto protoreflect.FileDescriptor

const file_cost_service_proto_rawDesc = "" +
	"\n" +
	"\x12cost_service.proto\x12\x0erestaurant_rpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\vtypes.proto\"\x90\x01\n" +
	"\bCostInfo\x12\x16\n" +
	"\x06costId\x18\x01 \x01(\rR\x06costId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x124\n" +
	"\bcostType\x18\x03 \x01(\x0e2\x18.restaurant_rpc.CostTypeR\bcostType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"N\n" +
	"\x0eGetAllCostResp\x12<\n" +
	"\fcostInfoList\x18\x01 \x03(\v2\x18.restaurant_rpc.CostInfoR\fcostInfoList2S\n" +
	"\vCostService\x12D\n" +
	"\n" +
	"GetAllCost\x12\x16.google.protobuf.Empty\x1a\x1e.restaurant_rpc.GetAllCostRespB'Z%restaurant_backend/rpc;restaurant_rpcb\x06proto3"

var (
	file_cost_service_proto_rawDescOnce sync.Once
	file_cost_service_proto_rawDescData []byte
)

func file_cost_service_proto_rawDescGZIP() []byte {
	file_cost_service_proto_rawDescOnce.Do(func() {
		file_cost_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cost_service_proto_rawDesc), len(file_cost_service_proto_rawDesc)))
	})
	return file_cost_service_proto_rawDescData
}

var file_cost_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cost_service_proto_goTypes = []any{
	(*CostInfo)(nil),       // 0: restaurant_rpc.CostInfo
	(*GetAllCostResp)(nil), // 1: restaurant_rpc.GetAllCostResp
	(CostType)(0),          // 2: restaurant_rpc.CostType
	(*emptypb.Empty)(nil),  // 3: google.protobuf.Empty
}
var file_cost_service_proto_depIdxs = []int32{
	2, // 0: restaurant_rpc.CostInfo.costType:type_name -> restaurant_rpc.CostType
	0, // 1: restaurant_rpc.GetAllCostResp.costInfoList:type_name -> restaurant_rpc.CostInfo
	3, // 2: restaurant_rpc.CostService.GetAllCost:input_type -> google.protobuf.Empty
	1, // 3: restaurant_rpc.CostService.GetAllCost:output_type -> restaurant_rpc.GetAllCostResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cost_service_proto_init() }
func file_cost_service_proto_init() {
	if File_cost_service_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cost_service_proto_rawDesc), len(file_cost_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cost_service_proto_goTypes,
		DependencyIndexes: file_cost_service_proto_depIdxs,
		MessageInfos:      file_cost_service_proto_msgTypes,
	}.Build()
	File_cost_service_proto = out.File
	file_cost_service_proto_goTypes = nil
	file_cost_service_proto_depIdxs = nil
}
