// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: dish_service.proto

package restaurant_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	types "restaurant_backend/restaurant_backend/types"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	DishType      *DishType              `protobuf:"bytes,4,opt,name=dishType,proto3" json:"dishType,omitempty"`
	Portions      []*DishPortion         `protobuf:"bytes,5,rep,name=portions,proto3" json:"portions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dish) Reset() {
	*x = Dish{}
	mi := &file_dish_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{0}
}

func (x *Dish) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dish) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Dish) GetDishType() *DishType {
	if x != nil {
		return x.DishType
	}
	return nil
}

func (x *Dish) GetPortions() []*DishPortion {
	if x != nil {
		return x.Portions
	}
	return nil
}

type DishPortion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`                                          // 价格, 以字符串传输避免精度丢失
	PortionType   types.DishPortion      `protobuf:"varint,4,opt,name=portionType,proto3,enum=restaurant.DishPortion" json:"portionType,omitempty"` // 份量
	Recipe        *Recipe                `protobuf:"bytes,5,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishPortion) Reset() {
	*x = DishPortion{}
	mi := &file_dish_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishPortion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishPortion) ProtoMessage() {}

func (x *DishPortion) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishPortion.ProtoReflect.Descriptor instead.
func (*DishPortion) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{1}
}

func (x *DishPortion) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DishPortion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DishPortion) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *DishPortion) GetPortionType() types.DishPortion {
	if x != nil {
		return x.PortionType
	}
	return types.DishPortion(0)
}

func (x *DishPortion) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type Recipe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Materials     []*RecipeMaterial      `protobuf:"bytes,2,rep,name=materials,proto3" json:"materials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	mi := &file_dish_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{2}
}

func (x *Recipe) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Recipe) GetMaterials() []*RecipeMaterial {
	if x != nil {
		return x.Materials
	}
	return nil
}

type RecipeMaterial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Material      *Material              `protobuf:"bytes,2,opt,name=material,proto3" json:"material,omitempty"`
	Quantity      string                 `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeMaterial) Reset() {
	*x = RecipeMaterial{}
	mi := &file_dish_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeMaterial) ProtoMessage() {}

func (x *RecipeMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeMaterial.ProtoReflect.Descriptor instead.
func (*RecipeMaterial) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{3}
}

func (x *RecipeMaterial) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecipeMaterial) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

func (x *RecipeMaterial) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type Material struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`                                 // 配料单价
	UnitType      types.UnitType         `protobuf:"varint,4,opt,name=unitType,proto3,enum=restaurant.UnitType" json:"unitType,omitempty"` // 配料单位
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`                               // 总量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Material) Reset() {
	*x = Material{}
	mi := &file_dish_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Material) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Material) ProtoMessage() {}

func (x *Material) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Material.ProtoReflect.Descriptor instead.
func (*Material) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{4}
}

func (x *Material) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Material) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Material) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Material) GetUnitType() types.UnitType {
	if x != nil {
		return x.UnitType
	}
	return types.UnitType(0)
}

func (x *Material) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type GetDishesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageInfo      *PageInfo              `protobuf:"bytes,1,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	Keywords      string                 `protobuf:"bytes,2,opt,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishesReq) Reset() {
	*x = GetDishesReq{}
	mi := &file_dish_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesReq) ProtoMessage() {}

func (x *GetDishesReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesReq.ProtoReflect.Descriptor instead.
func (*GetDishesReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetDishesReq) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *GetDishesReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

type GetDishesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*Dish                `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishesResp) Reset() {
	*x = GetDishesResp{}
	mi := &file_dish_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesResp) ProtoMessage() {}

func (x *GetDishesResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesResp.ProtoReflect.Descriptor instead.
func (*GetDishesResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetDishesResp) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

func (x *GetDishesResp) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type DishType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishTypeID    uint32                 `protobuf:"varint,1,opt,name=dishTypeID,proto3" json:"dishTypeID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishType) Reset() {
	*x = DishType{}
	mi := &file_dish_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishType) ProtoMessage() {}

func (x *DishType) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishType.ProtoReflect.Descriptor instead.
func (*DishType) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{7}
}

func (x *DishType) GetDishTypeID() uint32 {
	if x != nil {
		return x.DishTypeID
	}
	return 0
}

func (x *DishType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDishTypeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishTypes     []*DishType            `protobuf:"bytes,1,rep,name=dishTypes,proto3" json:"dishTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishTypeResp) Reset() {
	*x = GetDishTypeResp{}
	mi := &file_dish_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishTypeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishTypeResp) ProtoMessage() {}

func (x *GetDishTypeResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishTypeResp.ProtoReflect.Descriptor instead.
func (*GetDishTypeResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetDishTypeResp) GetDishTypes() []*DishType {
	if x != nil {
		return x.DishTypes
	}
	return nil
}

type AddDishTypeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=typeName,proto3" json:"typeName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDishTypeReq) Reset() {
	*x = AddDishTypeReq{}
	mi := &file_dish_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDishTypeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishTypeReq) ProtoMessage() {}

func (x *AddDishTypeReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishTypeReq.ProtoReflect.Descriptor instead.
func (*AddDishTypeReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{9}
}

func (x *AddDishTypeReq) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type AddDishTypeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishTypeID    uint32                 `protobuf:"varint,1,opt,name=dishTypeID,proto3" json:"dishTypeID,omitempty"`
	TypeName      string                 `protobuf:"bytes,2,opt,name=typeName,proto3" json:"typeName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDishTypeResp) Reset() {
	*x = AddDishTypeResp{}
	mi := &file_dish_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDishTypeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishTypeResp) ProtoMessage() {}

func (x *AddDishTypeResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishTypeResp.ProtoReflect.Descriptor instead.
func (*AddDishTypeResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{10}
}

func (x *AddDishTypeResp) GetDishTypeID() uint32 {
	if x != nil {
		return x.DishTypeID
	}
	return 0
}

func (x *AddDishTypeResp) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type GetMaterialsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageInfo      *PageInfo              `protobuf:"bytes,1,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	Keywords      string                 `protobuf:"bytes,2,opt,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaterialsReq) Reset() {
	*x = GetMaterialsReq{}
	mi := &file_dish_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaterialsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaterialsReq) ProtoMessage() {}

func (x *GetMaterialsReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaterialsReq.ProtoReflect.Descriptor instead.
func (*GetMaterialsReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetMaterialsReq) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *GetMaterialsReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

type GetMaterialsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialList  []*Material            `protobuf:"bytes,1,rep,name=materialList,proto3" json:"materialList,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaterialsResp) Reset() {
	*x = GetMaterialsResp{}
	mi := &file_dish_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaterialsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaterialsResp) ProtoMessage() {}

func (x *GetMaterialsResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaterialsResp.ProtoReflect.Descriptor instead.
func (*GetMaterialsResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetMaterialsResp) GetMaterialList() []*Material {
	if x != nil {
		return x.MaterialList
	}
	return nil
}

func (x *GetMaterialsResp) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type CreateOrEditMaterialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrEditMaterialReq) Reset() {
	*x = CreateOrEditMaterialReq{}
	mi := &file_dish_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrEditMaterialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrEditMaterialReq) ProtoMessage() {}

func (x *CreateOrEditMaterialReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrEditMaterialReq.ProtoReflect.Descriptor instead.
func (*CreateOrEditMaterialReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateOrEditMaterialReq) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

type CreateOrEditMaterialResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    uint32                 `protobuf:"varint,1,opt,name=materialId,proto3" json:"materialId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrEditMaterialResp) Reset() {
	*x = CreateOrEditMaterialResp{}
	mi := &file_dish_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrEditMaterialResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrEditMaterialResp) ProtoMessage() {}

func (x *CreateOrEditMaterialResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrEditMaterialResp.ProtoReflect.Descriptor instead.
func (*CreateOrEditMaterialResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{14}
}

func (x *CreateOrEditMaterialResp) GetMaterialId() uint32 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

type CreateOrEditDishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dish          *Dish                  `protobuf:"bytes,1,opt,name=dish,proto3" json:"dish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrEditDishReq) Reset() {
	*x = CreateOrEditDishReq{}
	mi := &file_dish_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrEditDishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrEditDishReq) ProtoMessage() {}

func (x *CreateOrEditDishReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrEditDishReq.ProtoReflect.Descriptor instead.
func (*CreateOrEditDishReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateOrEditDishReq) GetDish() *Dish {
	if x != nil {
		return x.Dish
	}
	return nil
}

type GetDishesWithCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageInfo      *PageInfo              `protobuf:"bytes,1,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	Category      *DishType              `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishesWithCategoryReq) Reset() {
	*x = GetDishesWithCategoryReq{}
	mi := &file_dish_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesWithCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesWithCategoryReq) ProtoMessage() {}

func (x *GetDishesWithCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesWithCategoryReq.ProtoReflect.Descriptor instead.
func (*GetDishesWithCategoryReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetDishesWithCategoryReq) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *GetDishesWithCategoryReq) GetCategory() *DishType {
	if x != nil {
		return x.Category
	}
	return nil
}

type GetDishesWithCategoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*Dish                `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	Category      *DishType              `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishesWithCategoryResp) Reset() {
	*x = GetDishesWithCategoryResp{}
	mi := &file_dish_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesWithCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesWithCategoryResp) ProtoMessage() {}

func (x *GetDishesWithCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesWithCategoryResp.ProtoReflect.Descriptor instead.
func (*GetDishesWithCategoryResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetDishesWithCategoryResp) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

func (x *GetDishesWithCategoryResp) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *GetDishesWithCategoryResp) GetCategory() *DishType {
	if x != nil {
		return x.Category
	}
	return nil
}

var File_dish_service_proto protoreflect.FileDescriptor

const file_dish_service_proto_rawDesc = "" +
	"\n" +
	"\x12dish_service.proto\x12\x0erestaurant_rpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto\x1a\x18restaurantV2/types.proto\"\xb5\x01\n" +
	"\x04Dish\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bimageUrl\x18\x03 \x01(\tR\bimageUrl\x124\n" +
	"\bdishType\x18\x04 \x01(\v2\x18.restaurant_rpc.DishTypeR\bdishType\x127\n" +
	"\bportions\x18\x05 \x03(\v2\x1b.restaurant_rpc.DishPortionR\bportions\"\xb2\x01\n" +
	"\vDishPortion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x129\n" +
	"\vportionType\x18\x04 \x01(\x0e2\x17.restaurant.DishPortionR\vportionType\x12.\n" +
	"\x06recipe\x18\x05 \x01(\v2\x16.restaurant_rpc.RecipeR\x06recipe\"V\n" +
	"\x06Recipe\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12<\n" +
	"\tmaterials\x18\x02 \x03(\v2\x1e.restaurant_rpc.RecipeMaterialR\tmaterials\"r\n" +
	"\x0eRecipeMaterial\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x124\n" +
	"\bmaterial\x18\x02 \x01(\v2\x18.restaurant_rpc.MaterialR\bmaterial\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\tR\bquantity\"\x8e\x01\n" +
	"\bMaterial\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x120\n" +
	"\bunitType\x18\x04 \x01(\x0e2\x14.restaurant.UnitTypeR\bunitType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\"`\n" +
	"\fGetDishesReq\x124\n" +
	"\bpageInfo\x18\x01 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\x12\x1a\n" +
	"\bkeywords\x18\x02 \x01(\tR\bkeywords\"s\n" +
	"\rGetDishesResp\x12,\n" +
	"\x06dishes\x18\x01 \x03(\v2\x14.restaurant_rpc.DishR\x06dishes\x124\n" +
	"\bpageInfo\x18\x02 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\">\n" +
	"\bDishType\x12\x1e\n" +
	"\n" +
	"dishTypeID\x18\x01 \x01(\rR\n" +
	"dishTypeID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\"I\n" +
	"\x0fGetDishTypeResp\x126\n" +
	"\tdishTypes\x18\x01 \x03(\v2\x18.restaurant_rpc.DishTypeR\tdishTypes\",\n" +
	"\x0eAddDishTypeReq\x12\x1a\n" +
	"\btypeName\x18\x01 \x01(\tR\btypeName\"M\n" +
	"\x0fAddDishTypeResp\x12\x1e\n" +
	"\n" +
	"dishTypeID\x18\x01 \x01(\rR\n" +
	"dishTypeID\x12\x1a\n" +
	"\btypeName\x18\x02 \x01(\tR\btypeName\"c\n" +
	"\x0fGetMaterialsReq\x124\n" +
	"\bpageInfo\x18\x01 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\x12\x1a\n" +
	"\bkeywords\x18\x02 \x01(\tR\bkeywords\"\x86\x01\n" +
	"\x10GetMaterialsResp\x12<\n" +
	"\fmaterialList\x18\x01 \x03(\v2\x18.restaurant_rpc.MaterialR\fmaterialList\x124\n" +
	"\bpageInfo\x18\x02 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\"O\n" +
	"\x17CreateOrEditMaterialReq\x124\n" +
	"\bmaterial\x18\x01 \x01(\v2\x18.restaurant_rpc.MaterialR\bmaterial\":\n" +
	"\x18CreateOrEditMaterialResp\x12\x1e\n" +
	"\n" +
	"materialId\x18\x01 \x01(\rR\n" +
	"materialId\"?\n" +
	"\x13CreateOrEditDishReq\x12(\n" +
	"\x04dish\x18\x01 \x01(\v2\x14.restaurant_rpc.DishR\x04dish\"\x86\x01\n" +
	"\x18GetDishesWithCategoryReq\x124\n" +
	"\bpageInfo\x18\x01 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\x124\n" +
	"\bcategory\x18\x02 \x01(\v2\x18.restaurant_rpc.DishTypeR\bcategory\"\xb5\x01\n" +
	"\x19GetDishesWithCategoryResp\x12,\n" +
	"\x06dishes\x18\x01 \x03(\v2\x14.restaurant_rpc.DishR\x06dishes\x124\n" +
	"\bpageInfo\x18\x02 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\x124\n" +
	"\bcategory\x18\x03 \x01(\v2\x18.restaurant_rpc.DishTypeR\bcategory2\xec\x04\n" +
	"\vDishService\x12H\n" +
	"\tGetDishes\x12\x1c.restaurant_rpc.GetDishesReq\x1a\x1d.restaurant_rpc.GetDishesResp\x12F\n" +
	"\vGetDishType\x12\x16.google.protobuf.Empty\x1a\x1f.restaurant_rpc.GetDishTypeResp\x12N\n" +
	"\vAddDishType\x12\x1e.restaurant_rpc.AddDishTypeReq\x1a\x1f.restaurant_rpc.AddDishTypeResp\x12Q\n" +
	"\fGetMaterials\x12\x1f.restaurant_rpc.GetMaterialsReq\x1a .restaurant_rpc.GetMaterialsResp\x12i\n" +
	"\x14CreateOrEditMaterial\x12'.restaurant_rpc.CreateOrEditMaterialReq\x1a(.restaurant_rpc.CreateOrEditMaterialResp\x12O\n" +
	"\x10CreateOrEditDish\x12#.restaurant_rpc.CreateOrEditDishReq\x1a\x16.google.protobuf.Empty\x12l\n" +
	"\x15GetDishesWithCategory\x12(.restaurant_rpc.GetDishesWithCategoryReq\x1a).restaurant_rpc.GetDishesWithCategoryRespB'Z%restaurant_backend/rpc;restaurant_rpcb\x06proto3"

var (
	file_dish_service_proto_rawDescOnce sync.Once
	file_dish_service_proto_rawDescData []byte
)

func file_dish_service_proto_rawDescGZIP() []byte {
	file_dish_service_proto_rawDescOnce.Do(func() {
		file_dish_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dish_service_proto_rawDesc), len(file_dish_service_proto_rawDesc)))
	})
	return file_dish_service_proto_rawDescData
}

var file_dish_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_dish_service_proto_goTypes = []any{
	(*Dish)(nil),                      // 0: restaurant_rpc.Dish
	(*DishPortion)(nil),               // 1: restaurant_rpc.DishPortion
	(*Recipe)(nil),                    // 2: restaurant_rpc.Recipe
	(*RecipeMaterial)(nil),            // 3: restaurant_rpc.RecipeMaterial
	(*Material)(nil),                  // 4: restaurant_rpc.Material
	(*GetDishesReq)(nil),              // 5: restaurant_rpc.GetDishesReq
	(*GetDishesResp)(nil),             // 6: restaurant_rpc.GetDishesResp
	(*DishType)(nil),                  // 7: restaurant_rpc.DishType
	(*GetDishTypeResp)(nil),           // 8: restaurant_rpc.GetDishTypeResp
	(*AddDishTypeReq)(nil),            // 9: restaurant_rpc.AddDishTypeReq
	(*AddDishTypeResp)(nil),           // 10: restaurant_rpc.AddDishTypeResp
	(*GetMaterialsReq)(nil),           // 11: restaurant_rpc.GetMaterialsReq
	(*GetMaterialsResp)(nil),          // 12: restaurant_rpc.GetMaterialsResp
	(*CreateOrEditMaterialReq)(nil),   // 13: restaurant_rpc.CreateOrEditMaterialReq
	(*CreateOrEditMaterialResp)(nil),  // 14: restaurant_rpc.CreateOrEditMaterialResp
	(*CreateOrEditDishReq)(nil),       // 15: restaurant_rpc.CreateOrEditDishReq
	(*GetDishesWithCategoryReq)(nil),  // 16: restaurant_rpc.GetDishesWithCategoryReq
	(*GetDishesWithCategoryResp)(nil), // 17: restaurant_rpc.GetDishesWithCategoryResp
	(types.DishPortion)(0),            // 18: restaurant.DishPortion
	(types.UnitType)(0),               // 19: restaurant.UnitType
	(*PageInfo)(nil),                  // 20: restaurant_rpc.PageInfo
	(*emptypb.Empty)(nil),             // 21: google.protobuf.Empty
}
var file_dish_service_proto_depIdxs = []int32{
	7,  // 0: restaurant_rpc.Dish.dishType:type_name -> restaurant_rpc.DishType
	1,  // 1: restaurant_rpc.Dish.portions:type_name -> restaurant_rpc.DishPortion
	18, // 2: restaurant_rpc.DishPortion.portionType:type_name -> restaurant.DishPortion
	2,  // 3: restaurant_rpc.DishPortion.recipe:type_name -> restaurant_rpc.Recipe
	3,  // 4: restaurant_rpc.Recipe.materials:type_name -> restaurant_rpc.RecipeMaterial
	4,  // 5: restaurant_rpc.RecipeMaterial.material:type_name -> restaurant_rpc.Material
	19, // 6: restaurant_rpc.Material.unitType:type_name -> restaurant.UnitType
	20, // 7: restaurant_rpc.GetDishesReq.pageInfo:type_name -> restaurant_rpc.PageInfo
	0,  // 8: restaurant_rpc.GetDishesResp.dishes:type_name -> restaurant_rpc.Dish
	20, // 9: restaurant_rpc.GetDishesResp.pageInfo:type_name -> restaurant_rpc.PageInfo
	7,  // 10: restaurant_rpc.GetDishTypeResp.dishTypes:type_name -> restaurant_rpc.DishType
	20, // 11: restaurant_rpc.GetMaterialsReq.pageInfo:type_name -> restaurant_rpc.PageInfo
	4,  // 12: restaurant_rpc.GetMaterialsResp.materialList:type_name -> restaurant_rpc.Material
	20, // 13: restaurant_rpc.GetMaterialsResp.pageInfo:type_name -> restaurant_rpc.PageInfo
	4,  // 14: restaurant_rpc.CreateOrEditMaterialReq.material:type_name -> restaurant_rpc.Material
	0,  // 15: restaurant_rpc.CreateOrEditDishReq.dish:type_name -> restaurant_rpc.Dish
	20, // 16: restaurant_rpc.GetDishesWithCategoryReq.pageInfo:type_name -> restaurant_rpc.PageInfo
	7,  // 17: restaurant_rpc.GetDishesWithCategoryReq.category:type_name -> restaurant_rpc.DishType
	0,  // 18: restaurant_rpc.GetDishesWithCategoryResp.dishes:type_name -> restaurant_rpc.Dish
	20, // 19: restaurant_rpc.GetDishesWithCategoryResp.pageInfo:type_name -> restaurant_rpc.PageInfo
	7,  // 20: restaurant_rpc.GetDishesWithCategoryResp.category:type_name -> restaurant_rpc.DishType
	5,  // 21: restaurant_rpc.DishService.GetDishes:input_type -> restaurant_rpc.GetDishesReq
	21, // 22: restaurant_rpc.DishService.GetDishType:input_type -> google.protobuf.Empty
	9,  // 23: restaurant_rpc.DishService.AddDishType:input_type -> restaurant_rpc.AddDishTypeReq
	11, // 24: restaurant_rpc.DishService.GetMaterials:input_type -> restaurant_rpc.GetMaterialsReq
	13, // 25: restaurant_rpc.DishService.CreateOrEditMaterial:input_type -> restaurant_rpc.CreateOrEditMaterialReq
	15, // 26: restaurant_rpc.DishService.CreateOrEditDish:input_type -> restaurant_rpc.CreateOrEditDishReq
	16, // 27: restaurant_rpc.DishService.GetDishesWithCategory:input_type -> restaurant_rpc.GetDishesWithCategoryReq
	6,  // 28: restaurant_rpc.DishService.GetDishes:output_type -> restaurant_rpc.GetDishesResp
	8,  // 29: restaurant_rpc.DishService.GetDishType:output_type -> restaurant_rpc.GetDishTypeResp
	10, // 30: restaurant_rpc.DishService.AddDishType:output_type -> restaurant_rpc.AddDishTypeResp
	12, // 31: restaurant_rpc.DishService.GetMaterials:output_type -> restaurant_rpc.GetMaterialsResp
	14, // 32: restaurant_rpc.DishService.CreateOrEditMaterial:output_type -> restaurant_rpc.CreateOrEditMaterialResp
	21, // 33: restaurant_rpc.DishService.CreateOrEditDish:output_type -> google.protobuf.Empty
	17, // 34: restaurant_rpc.DishService.GetDishesWithCategory:output_type -> restaurant_rpc.GetDishesWithCategoryResp
	28, // [28:35] is the sub-list for method output_type
	21, // [21:28] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_dish_service_proto_init() }
func file_dish_service_proto_init() {
	if File_dish_service_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dish_service_proto_rawDesc), len(file_dish_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dish_service_proto_goTypes,
		DependencyIndexes: file_dish_service_proto_depIdxs,
		MessageInfos:      file_dish_service_proto_msgTypes,
	}.Build()
	File_dish_service_proto = out.File
	file_dish_service_proto_goTypes = nil
	file_dish_service_proto_depIdxs = nil
}
