// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: dish_service.proto

package restaurant_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	DishType      *DishType              `protobuf:"bytes,4,opt,name=dishType,proto3" json:"dishType,omitempty"`
	Portions      []*DishPortion         `protobuf:"bytes,5,rep,name=portions,proto3" json:"portions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dish) Reset() {
	*x = Dish{}
	mi := &file_dish_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{0}
}

func (x *Dish) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dish) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Dish) GetDishType() *DishType {
	if x != nil {
		return x.DishType
	}
	return nil
}

func (x *Dish) GetPortions() []*DishPortion {
	if x != nil {
		return x.Portions
	}
	return nil
}

type DishPortion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`                                              // 价格, 以字符串传输避免精度丢失
	PortionType   PortionType            `protobuf:"varint,4,opt,name=portionType,proto3,enum=restaurant_rpc.PortionType" json:"portionType,omitempty"` // 份量
	Recipe        *Recipe                `protobuf:"bytes,5,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishPortion) Reset() {
	*x = DishPortion{}
	mi := &file_dish_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishPortion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishPortion) ProtoMessage() {}

func (x *DishPortion) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishPortion.ProtoReflect.Descriptor instead.
func (*DishPortion) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{1}
}

func (x *DishPortion) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DishPortion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DishPortion) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *DishPortion) GetPortionType() PortionType {
	if x != nil {
		return x.PortionType
	}
	return PortionType_DISH_PORTION_UNKNOWN
}

func (x *DishPortion) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type Recipe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Materials     []*RecipeMaterial      `protobuf:"bytes,2,rep,name=materials,proto3" json:"materials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	mi := &file_dish_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{2}
}

func (x *Recipe) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Recipe) GetMaterials() []*RecipeMaterial {
	if x != nil {
		return x.Materials
	}
	return nil
}

type RecipeMaterial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Material      *Material              `protobuf:"bytes,2,opt,name=material,proto3" json:"material,omitempty"`
	Quantity      string                 `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeMaterial) Reset() {
	*x = RecipeMaterial{}
	mi := &file_dish_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeMaterial) ProtoMessage() {}

func (x *RecipeMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeMaterial.ProtoReflect.Descriptor instead.
func (*RecipeMaterial) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{3}
}

func (x *RecipeMaterial) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecipeMaterial) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

func (x *RecipeMaterial) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type Material struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`                                     // 配料单价
	UnitType      UnitType               `protobuf:"varint,4,opt,name=unitType,proto3,enum=restaurant_rpc.UnitType" json:"unitType,omitempty"` // 配料单位
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`                                   // 总量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Material) Reset() {
	*x = Material{}
	mi := &file_dish_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Material) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Material) ProtoMessage() {}

func (x *Material) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Material.ProtoReflect.Descriptor instead.
func (*Material) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{4}
}

func (x *Material) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Material) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Material) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Material) GetUnitType() UnitType {
	if x != nil {
		return x.UnitType
	}
	return UnitType_UINT_TYPE_UNKNOWN
}

func (x *Material) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// / 座位
type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TableId       uint32                 `protobuf:"varint,2,opt,name=tableId,proto3" json:"tableId,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,3,opt,name=seatNumber,proto3" json:"seatNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_dish_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{5}
}

func (x *Seat) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Seat) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *Seat) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

// / 餐桌
type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Seats         []*Seat                `protobuf:"bytes,3,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_dish_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{6}
}

func (x *Table) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Table) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Table) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type GetDishesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageInfo      *PageInfo              `protobuf:"bytes,1,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	Keywords      string                 `protobuf:"bytes,2,opt,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishesReq) Reset() {
	*x = GetDishesReq{}
	mi := &file_dish_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesReq) ProtoMessage() {}

func (x *GetDishesReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesReq.ProtoReflect.Descriptor instead.
func (*GetDishesReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetDishesReq) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *GetDishesReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

type GetDishesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*Dish                `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishesResp) Reset() {
	*x = GetDishesResp{}
	mi := &file_dish_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesResp) ProtoMessage() {}

func (x *GetDishesResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesResp.ProtoReflect.Descriptor instead.
func (*GetDishesResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetDishesResp) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

func (x *GetDishesResp) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type DishType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishTypeID    uint32                 `protobuf:"varint,1,opt,name=dishTypeID,proto3" json:"dishTypeID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishType) Reset() {
	*x = DishType{}
	mi := &file_dish_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishType) ProtoMessage() {}

func (x *DishType) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishType.ProtoReflect.Descriptor instead.
func (*DishType) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{9}
}

func (x *DishType) GetDishTypeID() uint32 {
	if x != nil {
		return x.DishTypeID
	}
	return 0
}

func (x *DishType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDishTypeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishTypes     []*DishType            `protobuf:"bytes,1,rep,name=dishTypes,proto3" json:"dishTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishTypeResp) Reset() {
	*x = GetDishTypeResp{}
	mi := &file_dish_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishTypeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishTypeResp) ProtoMessage() {}

func (x *GetDishTypeResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishTypeResp.ProtoReflect.Descriptor instead.
func (*GetDishTypeResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetDishTypeResp) GetDishTypes() []*DishType {
	if x != nil {
		return x.DishTypes
	}
	return nil
}

type AddDishTypeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=typeName,proto3" json:"typeName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDishTypeReq) Reset() {
	*x = AddDishTypeReq{}
	mi := &file_dish_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDishTypeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishTypeReq) ProtoMessage() {}

func (x *AddDishTypeReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishTypeReq.ProtoReflect.Descriptor instead.
func (*AddDishTypeReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{11}
}

func (x *AddDishTypeReq) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type AddDishTypeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishTypeID    uint32                 `protobuf:"varint,1,opt,name=dishTypeID,proto3" json:"dishTypeID,omitempty"`
	TypeName      string                 `protobuf:"bytes,2,opt,name=typeName,proto3" json:"typeName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDishTypeResp) Reset() {
	*x = AddDishTypeResp{}
	mi := &file_dish_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDishTypeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishTypeResp) ProtoMessage() {}

func (x *AddDishTypeResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishTypeResp.ProtoReflect.Descriptor instead.
func (*AddDishTypeResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{12}
}

func (x *AddDishTypeResp) GetDishTypeID() uint32 {
	if x != nil {
		return x.DishTypeID
	}
	return 0
}

func (x *AddDishTypeResp) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type GetMaterialsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageInfo      *PageInfo              `protobuf:"bytes,1,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	Keywords      string                 `protobuf:"bytes,2,opt,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaterialsReq) Reset() {
	*x = GetMaterialsReq{}
	mi := &file_dish_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaterialsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaterialsReq) ProtoMessage() {}

func (x *GetMaterialsReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaterialsReq.ProtoReflect.Descriptor instead.
func (*GetMaterialsReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetMaterialsReq) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *GetMaterialsReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

type GetMaterialsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialList  []*Material            `protobuf:"bytes,1,rep,name=materialList,proto3" json:"materialList,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaterialsResp) Reset() {
	*x = GetMaterialsResp{}
	mi := &file_dish_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaterialsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaterialsResp) ProtoMessage() {}

func (x *GetMaterialsResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaterialsResp.ProtoReflect.Descriptor instead.
func (*GetMaterialsResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetMaterialsResp) GetMaterialList() []*Material {
	if x != nil {
		return x.MaterialList
	}
	return nil
}

func (x *GetMaterialsResp) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type CreateOrEditMaterialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrEditMaterialReq) Reset() {
	*x = CreateOrEditMaterialReq{}
	mi := &file_dish_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrEditMaterialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrEditMaterialReq) ProtoMessage() {}

func (x *CreateOrEditMaterialReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrEditMaterialReq.ProtoReflect.Descriptor instead.
func (*CreateOrEditMaterialReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateOrEditMaterialReq) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

type CreateOrEditMaterialResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    uint32                 `protobuf:"varint,1,opt,name=materialId,proto3" json:"materialId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrEditMaterialResp) Reset() {
	*x = CreateOrEditMaterialResp{}
	mi := &file_dish_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrEditMaterialResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrEditMaterialResp) ProtoMessage() {}

func (x *CreateOrEditMaterialResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrEditMaterialResp.ProtoReflect.Descriptor instead.
func (*CreateOrEditMaterialResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{16}
}

func (x *CreateOrEditMaterialResp) GetMaterialId() uint32 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

type CreateOrEditDishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dish          *Dish                  `protobuf:"bytes,1,opt,name=dish,proto3" json:"dish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrEditDishReq) Reset() {
	*x = CreateOrEditDishReq{}
	mi := &file_dish_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrEditDishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrEditDishReq) ProtoMessage() {}

func (x *CreateOrEditDishReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrEditDishReq.ProtoReflect.Descriptor instead.
func (*CreateOrEditDishReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{17}
}

func (x *CreateOrEditDishReq) GetDish() *Dish {
	if x != nil {
		return x.Dish
	}
	return nil
}

type GetDishesWithCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageInfo      *PageInfo              `protobuf:"bytes,1,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	Category      *DishType              `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishesWithCategoryReq) Reset() {
	*x = GetDishesWithCategoryReq{}
	mi := &file_dish_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesWithCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesWithCategoryReq) ProtoMessage() {}

func (x *GetDishesWithCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesWithCategoryReq.ProtoReflect.Descriptor instead.
func (*GetDishesWithCategoryReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetDishesWithCategoryReq) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *GetDishesWithCategoryReq) GetCategory() *DishType {
	if x != nil {
		return x.Category
	}
	return nil
}

type GetDishesWithCategoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*Dish                `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	Category      *DishType              `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishesWithCategoryResp) Reset() {
	*x = GetDishesWithCategoryResp{}
	mi := &file_dish_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesWithCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesWithCategoryResp) ProtoMessage() {}

func (x *GetDishesWithCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesWithCategoryResp.ProtoReflect.Descriptor instead.
func (*GetDishesWithCategoryResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetDishesWithCategoryResp) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

func (x *GetDishesWithCategoryResp) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *GetDishesWithCategoryResp) GetCategory() *DishType {
	if x != nil {
		return x.Category
	}
	return nil
}

type DeleteDishesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishIds       []uint32               `protobuf:"varint,1,rep,packed,name=dishIds,proto3" json:"dishIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDishesReq) Reset() {
	*x = DeleteDishesReq{}
	mi := &file_dish_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDishesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDishesReq) ProtoMessage() {}

func (x *DeleteDishesReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDishesReq.ProtoReflect.Descriptor instead.
func (*DeleteDishesReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteDishesReq) GetDishIds() []uint32 {
	if x != nil {
		return x.DishIds
	}
	return nil
}

type GetAllTablesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*Table               `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTablesResp) Reset() {
	*x = GetAllTablesResp{}
	mi := &file_dish_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTablesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTablesResp) ProtoMessage() {}

func (x *GetAllTablesResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTablesResp.ProtoReflect.Descriptor instead.
func (*GetAllTablesResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetAllTablesResp) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

type CreateOrEditTableReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *Table                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrEditTableReq) Reset() {
	*x = CreateOrEditTableReq{}
	mi := &file_dish_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrEditTableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrEditTableReq) ProtoMessage() {}

func (x *CreateOrEditTableReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrEditTableReq.ProtoReflect.Descriptor instead.
func (*CreateOrEditTableReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{22}
}

func (x *CreateOrEditTableReq) GetTable() *Table {
	if x != nil {
		return x.Table
	}
	return nil
}

type DeleteTableReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       uint32                 `protobuf:"varint,1,opt,name=tableId,proto3" json:"tableId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTableReq) Reset() {
	*x = DeleteTableReq{}
	mi := &file_dish_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTableReq) ProtoMessage() {}

func (x *DeleteTableReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTableReq.ProtoReflect.Descriptor instead.
func (*DeleteTableReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteTableReq) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

// / 订单基本组成部分
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishId        uint32                 `protobuf:"varint,1,opt,name=dishId,proto3" json:"dishId,omitempty"`
	PortionId     uint32                 `protobuf:"varint,2,opt,name=portionId,proto3" json:"portionId,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_dish_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{24}
}

func (x *OrderItem) GetDishId() uint32 {
	if x != nil {
		return x.DishId
	}
	return 0
}

func (x *OrderItem) GetPortionId() uint32 {
	if x != nil {
		return x.PortionId
	}
	return 0
}

func (x *OrderItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// / 下订单请求
type PlaceOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderItems    []*OrderItem           `protobuf:"bytes,1,rep,name=orderItems,proto3" json:"orderItems,omitempty"`
	OrderType     OrderType              `protobuf:"varint,2,opt,name=orderType,proto3,enum=restaurant_rpc.OrderType" json:"orderType,omitempty"` // 订单类型
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                                    // 订单地址, 仅外卖订单有该字段
	Table         *Table                 `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`                                        // 桌号, 仅堂食订单有该字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderReq) Reset() {
	*x = PlaceOrderReq{}
	mi := &file_dish_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderReq) ProtoMessage() {}

func (x *PlaceOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderReq.ProtoReflect.Descriptor instead.
func (*PlaceOrderReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{25}
}

func (x *PlaceOrderReq) GetOrderItems() []*OrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

func (x *PlaceOrderReq) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNKNOWN
}

func (x *PlaceOrderReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PlaceOrderReq) GetTable() *Table {
	if x != nil {
		return x.Table
	}
	return nil
}

// / 下订单响应
type PlaceOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint32                 `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResp) Reset() {
	*x = PlaceOrderResp{}
	mi := &file_dish_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResp) ProtoMessage() {}

func (x *PlaceOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResp.ProtoReflect.Descriptor instead.
func (*PlaceOrderResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{26}
}

func (x *PlaceOrderResp) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderInfoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishId        uint32                 `protobuf:"varint,1,opt,name=dishId,proto3" json:"dishId,omitempty"`
	PortionId     uint32                 `protobuf:"varint,2,opt,name=portionId,proto3" json:"portionId,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Dish          *Dish                  `protobuf:"bytes,4,opt,name=dish,proto3" json:"dish,omitempty"`
	Portion       *DishPortion           `protobuf:"bytes,5,opt,name=portion,proto3" json:"portion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoItem) Reset() {
	*x = OrderInfoItem{}
	mi := &file_dish_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoItem) ProtoMessage() {}

func (x *OrderInfoItem) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoItem.ProtoReflect.Descriptor instead.
func (*OrderInfoItem) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{27}
}

func (x *OrderInfoItem) GetDishId() uint32 {
	if x != nil {
		return x.DishId
	}
	return 0
}

func (x *OrderInfoItem) GetPortionId() uint32 {
	if x != nil {
		return x.PortionId
	}
	return 0
}

func (x *OrderInfoItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OrderInfoItem) GetDish() *Dish {
	if x != nil {
		return x.Dish
	}
	return nil
}

func (x *OrderInfoItem) GetPortion() *DishPortion {
	if x != nil {
		return x.Portion
	}
	return nil
}

// *
// 订单信息
type OrderInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        uint32                 `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	OrderType      OrderType              `protobuf:"varint,2,opt,name=orderType,proto3,enum=restaurant_rpc.OrderType" json:"orderType,omitempty"`
	Table          *Table                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	OrderInfoItems []*OrderInfoItem       `protobuf:"bytes,5,rep,name=orderInfoItems,proto3" json:"orderInfoItems,omitempty"`
	TotalPrice     string                 `protobuf:"bytes,6,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	CustomerId     uint32                 `protobuf:"varint,7,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Address        string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_dish_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{28}
}

func (x *OrderInfo) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderInfo) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNKNOWN
}

func (x *OrderInfo) GetTable() *Table {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *OrderInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *OrderInfo) GetOrderInfoItems() []*OrderInfoItem {
	if x != nil {
		return x.OrderInfoItems
	}
	return nil
}

func (x *OrderInfo) GetTotalPrice() string {
	if x != nil {
		return x.TotalPrice
	}
	return ""
}

func (x *OrderInfo) GetCustomerId() uint32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *OrderInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetOrderInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint32                 `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderInfoReq) Reset() {
	*x = GetOrderInfoReq{}
	mi := &file_dish_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoReq) ProtoMessage() {}

func (x *GetOrderInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoReq.ProtoReflect.Descriptor instead.
func (*GetOrderInfoReq) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{29}
}

func (x *GetOrderInfoReq) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderInfo     *OrderInfo             `protobuf:"bytes,1,opt,name=orderInfo,proto3" json:"orderInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderInfoResp) Reset() {
	*x = GetOrderInfoResp{}
	mi := &file_dish_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoResp) ProtoMessage() {}

func (x *GetOrderInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoResp.ProtoReflect.Descriptor instead.
func (*GetOrderInfoResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{30}
}

func (x *GetOrderInfoResp) GetOrderInfo() *OrderInfo {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

// / 订单简略信息
type OrderSimpleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint32                 `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`      // 订单ID
	TotalPrice    string                 `protobuf:"bytes,2,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"` // 订单总价
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`  // 订单创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSimpleInfo) Reset() {
	*x = OrderSimpleInfo{}
	mi := &file_dish_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSimpleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSimpleInfo) ProtoMessage() {}

func (x *OrderSimpleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSimpleInfo.ProtoReflect.Descriptor instead.
func (*OrderSimpleInfo) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{31}
}

func (x *OrderSimpleInfo) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderSimpleInfo) GetTotalPrice() string {
	if x != nil {
		return x.TotalPrice
	}
	return ""
}

func (x *OrderSimpleInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetAllOrdersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderInfoList []*OrderSimpleInfo     `protobuf:"bytes,1,rep,name=orderInfoList,proto3" json:"orderInfoList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOrdersResp) Reset() {
	*x = GetAllOrdersResp{}
	mi := &file_dish_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrdersResp) ProtoMessage() {}

func (x *GetAllOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrdersResp.ProtoReflect.Descriptor instead.
func (*GetAllOrdersResp) Descriptor() ([]byte, []int) {
	return file_dish_service_proto_rawDescGZIP(), []int{32}
}

func (x *GetAllOrdersResp) GetOrderInfoList() []*OrderSimpleInfo {
	if x != nil {
		return x.OrderInfoList
	}
	return nil
}

var File_dish_service_proto protoreflect.FileDescriptor

const file_dish_service_proto_rawDesc = "" +
	"\n" +
	"\x12dish_service.proto\x12\x0erestaurant_rpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto\x1a\vtypes.proto\"\xb5\x01\n" +
	"\x04Dish\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bimageUrl\x18\x03 \x01(\tR\bimageUrl\x124\n" +
	"\bdishType\x18\x04 \x01(\v2\x18.restaurant_rpc.DishTypeR\bdishType\x127\n" +
	"\bportions\x18\x05 \x03(\v2\x1b.restaurant_rpc.DishPortionR\bportions\"\xb6\x01\n" +
	"\vDishPortion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12=\n" +
	"\vportionType\x18\x04 \x01(\x0e2\x1b.restaurant_rpc.PortionTypeR\vportionType\x12.\n" +
	"\x06recipe\x18\x05 \x01(\v2\x16.restaurant_rpc.RecipeR\x06recipe\"V\n" +
	"\x06Recipe\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12<\n" +
	"\tmaterials\x18\x02 \x03(\v2\x1e.restaurant_rpc.RecipeMaterialR\tmaterials\"r\n" +
	"\x0eRecipeMaterial\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x124\n" +
	"\bmaterial\x18\x02 \x01(\v2\x18.restaurant_rpc.MaterialR\bmaterial\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\tR\bquantity\"\x92\x01\n" +
	"\bMaterial\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x124\n" +
	"\bunitType\x18\x04 \x01(\x0e2\x18.restaurant_rpc.UnitTypeR\bunitType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\"P\n" +
	"\x04Seat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\atableId\x18\x02 \x01(\rR\atableId\x12\x1e\n" +
	"\n" +
	"seatNumber\x18\x03 \x01(\tR\n" +
	"seatNumber\"[\n" +
	"\x05Table\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12*\n" +
	"\x05seats\x18\x03 \x03(\v2\x14.restaurant_rpc.SeatR\x05seats\"`\n" +
	"\fGetDishesReq\x124\n" +
	"\bpageInfo\x18\x01 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\x12\x1a\n" +
	"\bkeywords\x18\x02 \x01(\tR\bkeywords\"s\n" +
	"\rGetDishesResp\x12,\n" +
	"\x06dishes\x18\x01 \x03(\v2\x14.restaurant_rpc.DishR\x06dishes\x124\n" +
	"\bpageInfo\x18\x02 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\">\n" +
	"\bDishType\x12\x1e\n" +
	"\n" +
	"dishTypeID\x18\x01 \x01(\rR\n" +
	"dishTypeID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\"I\n" +
	"\x0fGetDishTypeResp\x126\n" +
	"\tdishTypes\x18\x01 \x03(\v2\x18.restaurant_rpc.DishTypeR\tdishTypes\",\n" +
	"\x0eAddDishTypeReq\x12\x1a\n" +
	"\btypeName\x18\x01 \x01(\tR\btypeName\"M\n" +
	"\x0fAddDishTypeResp\x12\x1e\n" +
	"\n" +
	"dishTypeID\x18\x01 \x01(\rR\n" +
	"dishTypeID\x12\x1a\n" +
	"\btypeName\x18\x02 \x01(\tR\btypeName\"c\n" +
	"\x0fGetMaterialsReq\x124\n" +
	"\bpageInfo\x18\x01 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\x12\x1a\n" +
	"\bkeywords\x18\x02 \x01(\tR\bkeywords\"\x86\x01\n" +
	"\x10GetMaterialsResp\x12<\n" +
	"\fmaterialList\x18\x01 \x03(\v2\x18.restaurant_rpc.MaterialR\fmaterialList\x124\n" +
	"\bpageInfo\x18\x02 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\"O\n" +
	"\x17CreateOrEditMaterialReq\x124\n" +
	"\bmaterial\x18\x01 \x01(\v2\x18.restaurant_rpc.MaterialR\bmaterial\":\n" +
	"\x18CreateOrEditMaterialResp\x12\x1e\n" +
	"\n" +
	"materialId\x18\x01 \x01(\rR\n" +
	"materialId\"?\n" +
	"\x13CreateOrEditDishReq\x12(\n" +
	"\x04dish\x18\x01 \x01(\v2\x14.restaurant_rpc.DishR\x04dish\"\x86\x01\n" +
	"\x18GetDishesWithCategoryReq\x124\n" +
	"\bpageInfo\x18\x01 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\x124\n" +
	"\bcategory\x18\x02 \x01(\v2\x18.restaurant_rpc.DishTypeR\bcategory\"\xb5\x01\n" +
	"\x19GetDishesWithCategoryResp\x12,\n" +
	"\x06dishes\x18\x01 \x03(\v2\x14.restaurant_rpc.DishR\x06dishes\x124\n" +
	"\bpageInfo\x18\x02 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\x124\n" +
	"\bcategory\x18\x03 \x01(\v2\x18.restaurant_rpc.DishTypeR\bcategory\"+\n" +
	"\x0fDeleteDishesReq\x12\x18\n" +
	"\adishIds\x18\x01 \x03(\rR\adishIds\"A\n" +
	"\x10GetAllTablesResp\x12-\n" +
	"\x06tables\x18\x01 \x03(\v2\x15.restaurant_rpc.TableR\x06tables\"C\n" +
	"\x14CreateOrEditTableReq\x12+\n" +
	"\x05table\x18\x01 \x01(\v2\x15.restaurant_rpc.TableR\x05table\"*\n" +
	"\x0eDeleteTableReq\x12\x18\n" +
	"\atableId\x18\x01 \x01(\rR\atableId\"W\n" +
	"\tOrderItem\x12\x16\n" +
	"\x06dishId\x18\x01 \x01(\rR\x06dishId\x12\x1c\n" +
	"\tportionId\x18\x02 \x01(\rR\tportionId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"\xca\x01\n" +
	"\rPlaceOrderReq\x129\n" +
	"\n" +
	"orderItems\x18\x01 \x03(\v2\x19.restaurant_rpc.OrderItemR\n" +
	"orderItems\x127\n" +
	"\torderType\x18\x02 \x01(\x0e2\x19.restaurant_rpc.OrderTypeR\torderType\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12+\n" +
	"\x05table\x18\x04 \x01(\v2\x15.restaurant_rpc.TableR\x05table\"*\n" +
	"\x0ePlaceOrderResp\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\rR\aorderId\"\xbc\x01\n" +
	"\rOrderInfoItem\x12\x16\n" +
	"\x06dishId\x18\x01 \x01(\rR\x06dishId\x12\x1c\n" +
	"\tportionId\x18\x02 \x01(\rR\tportionId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12(\n" +
	"\x04dish\x18\x04 \x01(\v2\x14.restaurant_rpc.DishR\x04dish\x125\n" +
	"\aportion\x18\x05 \x01(\v2\x1b.restaurant_rpc.DishPortionR\aportion\"\xca\x02\n" +
	"\tOrderInfo\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\rR\aorderId\x127\n" +
	"\torderType\x18\x02 \x01(\x0e2\x19.restaurant_rpc.OrderTypeR\torderType\x12+\n" +
	"\x05table\x18\x03 \x01(\v2\x15.restaurant_rpc.TableR\x05table\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\x03R\tcreatedAt\x12E\n" +
	"\x0eorderInfoItems\x18\x05 \x03(\v2\x1d.restaurant_rpc.OrderInfoItemR\x0eorderInfoItems\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x06 \x01(\tR\n" +
	"totalPrice\x12\x1e\n" +
	"\n" +
	"customerId\x18\a \x01(\rR\n" +
	"customerId\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\"+\n" +
	"\x0fGetOrderInfoReq\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\rR\aorderId\"K\n" +
	"\x10GetOrderInfoResp\x127\n" +
	"\torderInfo\x18\x01 \x01(\v2\x19.restaurant_rpc.OrderInfoR\torderInfo\"i\n" +
	"\x0fOrderSimpleInfo\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\rR\aorderId\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x02 \x01(\tR\n" +
	"totalPrice\x12\x1c\n" +
	"\tcreatedAt\x18\x03 \x01(\x03R\tcreatedAt\"Y\n" +
	"\x10GetAllOrdersResp\x12E\n" +
	"\rorderInfoList\x18\x01 \x03(\v2\x1f.restaurant_rpc.OrderSimpleInfoR\rorderInfoList2\x83\t\n" +
	"\vDishService\x12H\n" +
	"\tGetDishes\x12\x1c.restaurant_rpc.GetDishesReq\x1a\x1d.restaurant_rpc.GetDishesResp\x12F\n" +
	"\vGetDishType\x12\x16.google.protobuf.Empty\x1a\x1f.restaurant_rpc.GetDishTypeResp\x12N\n" +
	"\vAddDishType\x12\x1e.restaurant_rpc.AddDishTypeReq\x1a\x1f.restaurant_rpc.AddDishTypeResp\x12Q\n" +
	"\fGetMaterials\x12\x1f.restaurant_rpc.GetMaterialsReq\x1a .restaurant_rpc.GetMaterialsResp\x12i\n" +
	"\x14CreateOrEditMaterial\x12'.restaurant_rpc.CreateOrEditMaterialReq\x1a(.restaurant_rpc.CreateOrEditMaterialResp\x12O\n" +
	"\x10CreateOrEditDish\x12#.restaurant_rpc.CreateOrEditDishReq\x1a\x16.google.protobuf.Empty\x12l\n" +
	"\x15GetDishesWithCategory\x12(.restaurant_rpc.GetDishesWithCategoryReq\x1a).restaurant_rpc.GetDishesWithCategoryResp\x12G\n" +
	"\fDeleteDishes\x12\x1f.restaurant_rpc.DeleteDishesReq\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\fGetAllTables\x12\x16.google.protobuf.Empty\x1a .restaurant_rpc.GetAllTablesResp\x12Q\n" +
	"\x11CreateOrEditTable\x12$.restaurant_rpc.CreateOrEditTableReq\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\vDeleteTable\x12\x1e.restaurant_rpc.DeleteTableReq\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\n" +
	"PlaceOrder\x12\x1d.restaurant_rpc.PlaceOrderReq\x1a\x1e.restaurant_rpc.PlaceOrderResp\x12Q\n" +
	"\fGetOrderInfo\x12\x1f.restaurant_rpc.GetOrderInfoReq\x1a .restaurant_rpc.GetOrderInfoResp\x12H\n" +
	"\fGetAllOrders\x12\x16.google.protobuf.Empty\x1a .restaurant_rpc.GetAllOrdersRespB'Z%restaurant_backend/rpc;restaurant_rpcb\x06proto3"

var (
	file_dish_service_proto_rawDescOnce sync.Once
	file_dish_service_proto_rawDescData []byte
)

func file_dish_service_proto_rawDescGZIP() []byte {
	file_dish_service_proto_rawDescOnce.Do(func() {
		file_dish_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dish_service_proto_rawDesc), len(file_dish_service_proto_rawDesc)))
	})
	return file_dish_service_proto_rawDescData
}

var file_dish_service_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_dish_service_proto_goTypes = []any{
	(*Dish)(nil),                      // 0: restaurant_rpc.Dish
	(*DishPortion)(nil),               // 1: restaurant_rpc.DishPortion
	(*Recipe)(nil),                    // 2: restaurant_rpc.Recipe
	(*RecipeMaterial)(nil),            // 3: restaurant_rpc.RecipeMaterial
	(*Material)(nil),                  // 4: restaurant_rpc.Material
	(*Seat)(nil),                      // 5: restaurant_rpc.Seat
	(*Table)(nil),                     // 6: restaurant_rpc.Table
	(*GetDishesReq)(nil),              // 7: restaurant_rpc.GetDishesReq
	(*GetDishesResp)(nil),             // 8: restaurant_rpc.GetDishesResp
	(*DishType)(nil),                  // 9: restaurant_rpc.DishType
	(*GetDishTypeResp)(nil),           // 10: restaurant_rpc.GetDishTypeResp
	(*AddDishTypeReq)(nil),            // 11: restaurant_rpc.AddDishTypeReq
	(*AddDishTypeResp)(nil),           // 12: restaurant_rpc.AddDishTypeResp
	(*GetMaterialsReq)(nil),           // 13: restaurant_rpc.GetMaterialsReq
	(*GetMaterialsResp)(nil),          // 14: restaurant_rpc.GetMaterialsResp
	(*CreateOrEditMaterialReq)(nil),   // 15: restaurant_rpc.CreateOrEditMaterialReq
	(*CreateOrEditMaterialResp)(nil),  // 16: restaurant_rpc.CreateOrEditMaterialResp
	(*CreateOrEditDishReq)(nil),       // 17: restaurant_rpc.CreateOrEditDishReq
	(*GetDishesWithCategoryReq)(nil),  // 18: restaurant_rpc.GetDishesWithCategoryReq
	(*GetDishesWithCategoryResp)(nil), // 19: restaurant_rpc.GetDishesWithCategoryResp
	(*DeleteDishesReq)(nil),           // 20: restaurant_rpc.DeleteDishesReq
	(*GetAllTablesResp)(nil),          // 21: restaurant_rpc.GetAllTablesResp
	(*CreateOrEditTableReq)(nil),      // 22: restaurant_rpc.CreateOrEditTableReq
	(*DeleteTableReq)(nil),            // 23: restaurant_rpc.DeleteTableReq
	(*OrderItem)(nil),                 // 24: restaurant_rpc.OrderItem
	(*PlaceOrderReq)(nil),             // 25: restaurant_rpc.PlaceOrderReq
	(*PlaceOrderResp)(nil),            // 26: restaurant_rpc.PlaceOrderResp
	(*OrderInfoItem)(nil),             // 27: restaurant_rpc.OrderInfoItem
	(*OrderInfo)(nil),                 // 28: restaurant_rpc.OrderInfo
	(*GetOrderInfoReq)(nil),           // 29: restaurant_rpc.GetOrderInfoReq
	(*GetOrderInfoResp)(nil),          // 30: restaurant_rpc.GetOrderInfoResp
	(*OrderSimpleInfo)(nil),           // 31: restaurant_rpc.OrderSimpleInfo
	(*GetAllOrdersResp)(nil),          // 32: restaurant_rpc.GetAllOrdersResp
	(PortionType)(0),                  // 33: restaurant_rpc.PortionType
	(UnitType)(0),                     // 34: restaurant_rpc.UnitType
	(*PageInfo)(nil),                  // 35: restaurant_rpc.PageInfo
	(OrderType)(0),                    // 36: restaurant_rpc.OrderType
	(*emptypb.Empty)(nil),             // 37: google.protobuf.Empty
}
var file_dish_service_proto_depIdxs = []int32{
	9,  // 0: restaurant_rpc.Dish.dishType:type_name -> restaurant_rpc.DishType
	1,  // 1: restaurant_rpc.Dish.portions:type_name -> restaurant_rpc.DishPortion
	33, // 2: restaurant_rpc.DishPortion.portionType:type_name -> restaurant_rpc.PortionType
	2,  // 3: restaurant_rpc.DishPortion.recipe:type_name -> restaurant_rpc.Recipe
	3,  // 4: restaurant_rpc.Recipe.materials:type_name -> restaurant_rpc.RecipeMaterial
	4,  // 5: restaurant_rpc.RecipeMaterial.material:type_name -> restaurant_rpc.Material
	34, // 6: restaurant_rpc.Material.unitType:type_name -> restaurant_rpc.UnitType
	5,  // 7: restaurant_rpc.Table.seats:type_name -> restaurant_rpc.Seat
	35, // 8: restaurant_rpc.GetDishesReq.pageInfo:type_name -> restaurant_rpc.PageInfo
	0,  // 9: restaurant_rpc.GetDishesResp.dishes:type_name -> restaurant_rpc.Dish
	35, // 10: restaurant_rpc.GetDishesResp.pageInfo:type_name -> restaurant_rpc.PageInfo
	9,  // 11: restaurant_rpc.GetDishTypeResp.dishTypes:type_name -> restaurant_rpc.DishType
	35, // 12: restaurant_rpc.GetMaterialsReq.pageInfo:type_name -> restaurant_rpc.PageInfo
	4,  // 13: restaurant_rpc.GetMaterialsResp.materialList:type_name -> restaurant_rpc.Material
	35, // 14: restaurant_rpc.GetMaterialsResp.pageInfo:type_name -> restaurant_rpc.PageInfo
	4,  // 15: restaurant_rpc.CreateOrEditMaterialReq.material:type_name -> restaurant_rpc.Material
	0,  // 16: restaurant_rpc.CreateOrEditDishReq.dish:type_name -> restaurant_rpc.Dish
	35, // 17: restaurant_rpc.GetDishesWithCategoryReq.pageInfo:type_name -> restaurant_rpc.PageInfo
	9,  // 18: restaurant_rpc.GetDishesWithCategoryReq.category:type_name -> restaurant_rpc.DishType
	0,  // 19: restaurant_rpc.GetDishesWithCategoryResp.dishes:type_name -> restaurant_rpc.Dish
	35, // 20: restaurant_rpc.GetDishesWithCategoryResp.pageInfo:type_name -> restaurant_rpc.PageInfo
	9,  // 21: restaurant_rpc.GetDishesWithCategoryResp.category:type_name -> restaurant_rpc.DishType
	6,  // 22: restaurant_rpc.GetAllTablesResp.tables:type_name -> restaurant_rpc.Table
	6,  // 23: restaurant_rpc.CreateOrEditTableReq.table:type_name -> restaurant_rpc.Table
	24, // 24: restaurant_rpc.PlaceOrderReq.orderItems:type_name -> restaurant_rpc.OrderItem
	36, // 25: restaurant_rpc.PlaceOrderReq.orderType:type_name -> restaurant_rpc.OrderType
	6,  // 26: restaurant_rpc.PlaceOrderReq.table:type_name -> restaurant_rpc.Table
	0,  // 27: restaurant_rpc.OrderInfoItem.dish:type_name -> restaurant_rpc.Dish
	1,  // 28: restaurant_rpc.OrderInfoItem.portion:type_name -> restaurant_rpc.DishPortion
	36, // 29: restaurant_rpc.OrderInfo.orderType:type_name -> restaurant_rpc.OrderType
	6,  // 30: restaurant_rpc.OrderInfo.table:type_name -> restaurant_rpc.Table
	27, // 31: restaurant_rpc.OrderInfo.orderInfoItems:type_name -> restaurant_rpc.OrderInfoItem
	28, // 32: restaurant_rpc.GetOrderInfoResp.orderInfo:type_name -> restaurant_rpc.OrderInfo
	31, // 33: restaurant_rpc.GetAllOrdersResp.orderInfoList:type_name -> restaurant_rpc.OrderSimpleInfo
	7,  // 34: restaurant_rpc.DishService.GetDishes:input_type -> restaurant_rpc.GetDishesReq
	37, // 35: restaurant_rpc.DishService.GetDishType:input_type -> google.protobuf.Empty
	11, // 36: restaurant_rpc.DishService.AddDishType:input_type -> restaurant_rpc.AddDishTypeReq
	13, // 37: restaurant_rpc.DishService.GetMaterials:input_type -> restaurant_rpc.GetMaterialsReq
	15, // 38: restaurant_rpc.DishService.CreateOrEditMaterial:input_type -> restaurant_rpc.CreateOrEditMaterialReq
	17, // 39: restaurant_rpc.DishService.CreateOrEditDish:input_type -> restaurant_rpc.CreateOrEditDishReq
	18, // 40: restaurant_rpc.DishService.GetDishesWithCategory:input_type -> restaurant_rpc.GetDishesWithCategoryReq
	20, // 41: restaurant_rpc.DishService.DeleteDishes:input_type -> restaurant_rpc.DeleteDishesReq
	37, // 42: restaurant_rpc.DishService.GetAllTables:input_type -> google.protobuf.Empty
	22, // 43: restaurant_rpc.DishService.CreateOrEditTable:input_type -> restaurant_rpc.CreateOrEditTableReq
	23, // 44: restaurant_rpc.DishService.DeleteTable:input_type -> restaurant_rpc.DeleteTableReq
	25, // 45: restaurant_rpc.DishService.PlaceOrder:input_type -> restaurant_rpc.PlaceOrderReq
	29, // 46: restaurant_rpc.DishService.GetOrderInfo:input_type -> restaurant_rpc.GetOrderInfoReq
	37, // 47: restaurant_rpc.DishService.GetAllOrders:input_type -> google.protobuf.Empty
	8,  // 48: restaurant_rpc.DishService.GetDishes:output_type -> restaurant_rpc.GetDishesResp
	10, // 49: restaurant_rpc.DishService.GetDishType:output_type -> restaurant_rpc.GetDishTypeResp
	12, // 50: restaurant_rpc.DishService.AddDishType:output_type -> restaurant_rpc.AddDishTypeResp
	14, // 51: restaurant_rpc.DishService.GetMaterials:output_type -> restaurant_rpc.GetMaterialsResp
	16, // 52: restaurant_rpc.DishService.CreateOrEditMaterial:output_type -> restaurant_rpc.CreateOrEditMaterialResp
	37, // 53: restaurant_rpc.DishService.CreateOrEditDish:output_type -> google.protobuf.Empty
	19, // 54: restaurant_rpc.DishService.GetDishesWithCategory:output_type -> restaurant_rpc.GetDishesWithCategoryResp
	37, // 55: restaurant_rpc.DishService.DeleteDishes:output_type -> google.protobuf.Empty
	21, // 56: restaurant_rpc.DishService.GetAllTables:output_type -> restaurant_rpc.GetAllTablesResp
	37, // 57: restaurant_rpc.DishService.CreateOrEditTable:output_type -> google.protobuf.Empty
	37, // 58: restaurant_rpc.DishService.DeleteTable:output_type -> google.protobuf.Empty
	26, // 59: restaurant_rpc.DishService.PlaceOrder:output_type -> restaurant_rpc.PlaceOrderResp
	30, // 60: restaurant_rpc.DishService.GetOrderInfo:output_type -> restaurant_rpc.GetOrderInfoResp
	32, // 61: restaurant_rpc.DishService.GetAllOrders:output_type -> restaurant_rpc.GetAllOrdersResp
	48, // [48:62] is the sub-list for method output_type
	34, // [34:48] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_dish_service_proto_init() }
func file_dish_service_proto_init() {
	if File_dish_service_proto != nil {
		return
	}
	file_common_proto_init()
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dish_service_proto_rawDesc), len(file_dish_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dish_service_proto_goTypes,
		DependencyIndexes: file_dish_service_proto_depIdxs,
		MessageInfos:      file_dish_service_proto_msgTypes,
	}.Build()
	File_dish_service_proto = out.File
	file_dish_service_proto_goTypes = nil
	file_dish_service_proto_depIdxs = nil
}
