// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: employee_service.proto

package restaurant_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmployeeListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageInfo      *PageInfo              `protobuf:"bytes,1,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	Keywords      string                 `protobuf:"bytes,2,opt,name=keywords,proto3" json:"keywords,omitempty"` // 搜索关键词: 员工姓名、手机号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeListReq) Reset() {
	*x = EmployeeListReq{}
	mi := &file_employee_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeListReq) ProtoMessage() {}

func (x *EmployeeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeListReq.ProtoReflect.Descriptor instead.
func (*EmployeeListReq) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{0}
}

func (x *EmployeeListReq) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *EmployeeListReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

type EmployeeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          EmployeeRole           `protobuf:"varint,4,opt,name=role,proto3,enum=restaurant_rpc.EmployeeRole" json:"role,omitempty"`
	Salary        string                 `protobuf:"bytes,5,opt,name=salary,proto3" json:"salary,omitempty"`       // 工资以字符串的形式传递, 防止精度丢失
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"` // unix时间戳
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` // unix时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeInfo) Reset() {
	*x = EmployeeInfo{}
	mi := &file_employee_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeInfo) ProtoMessage() {}

func (x *EmployeeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeInfo.ProtoReflect.Descriptor instead.
func (*EmployeeInfo) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmployeeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmployeeInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *EmployeeInfo) GetRole() EmployeeRole {
	if x != nil {
		return x.Role
	}
	return EmployeeRole_ROLE_UNKNOWN
}

func (x *EmployeeInfo) GetSalary() string {
	if x != nil {
		return x.Salary
	}
	return ""
}

func (x *EmployeeInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EmployeeInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type EmployeeListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeList  []*EmployeeInfo        `protobuf:"bytes,1,rep,name=employeeList,proto3" json:"employeeList,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeListResp) Reset() {
	*x = EmployeeListResp{}
	mi := &file_employee_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeListResp) ProtoMessage() {}

func (x *EmployeeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeListResp.ProtoReflect.Descriptor instead.
func (*EmployeeListResp) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{2}
}

func (x *EmployeeListResp) GetEmployeeList() []*EmployeeInfo {
	if x != nil {
		return x.EmployeeList
	}
	return nil
}

func (x *EmployeeListResp) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type AddEmployeeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeName  string                 `protobuf:"bytes,1,opt,name=employeeName,proto3" json:"employeeName,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role          EmployeeRole           `protobuf:"varint,4,opt,name=role,proto3,enum=restaurant_rpc.EmployeeRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEmployeeReq) Reset() {
	*x = AddEmployeeReq{}
	mi := &file_employee_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEmployeeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEmployeeReq) ProtoMessage() {}

func (x *AddEmployeeReq) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEmployeeReq.ProtoReflect.Descriptor instead.
func (*AddEmployeeReq) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{3}
}

func (x *AddEmployeeReq) GetEmployeeName() string {
	if x != nil {
		return x.EmployeeName
	}
	return ""
}

func (x *AddEmployeeReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AddEmployeeReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AddEmployeeReq) GetRole() EmployeeRole {
	if x != nil {
		return x.Role
	}
	return EmployeeRole_ROLE_UNKNOWN
}

type AddEmployeeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0: 成功, 其余均为失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEmployeeResp) Reset() {
	*x = AddEmployeeResp{}
	mi := &file_employee_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEmployeeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEmployeeResp) ProtoMessage() {}

func (x *AddEmployeeResp) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEmployeeResp.ProtoReflect.Descriptor instead.
func (*AddEmployeeResp) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddEmployeeResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddEmployeeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_employee_service_proto protoreflect.FileDescriptor

const file_employee_service_proto_rawDesc = "" +
	"\n" +
	"\x16employee_service.proto\x12\x0erestaurant_rpc\x1a\x13basic_service.proto\x1a\fcommon.proto\"c\n" +
	"\x0fEmployeeListReq\x124\n" +
	"\bpageInfo\x18\x01 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\x12\x1a\n" +
	"\bkeywords\x18\x02 \x01(\tR\bkeywords\"\xce\x01\n" +
	"\fEmployeeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x120\n" +
	"\x04role\x18\x04 \x01(\x0e2\x1c.restaurant_rpc.EmployeeRoleR\x04role\x12\x16\n" +
	"\x06salary\x18\x05 \x01(\tR\x06salary\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\a \x01(\tR\tupdatedAt\"\x8a\x01\n" +
	"\x10EmployeeListResp\x12@\n" +
	"\femployeeList\x18\x01 \x03(\v2\x1c.restaurant_rpc.EmployeeInfoR\femployeeList\x124\n" +
	"\bpageInfo\x18\x02 \x01(\v2\x18.restaurant_rpc.PageInfoR\bpageInfo\"\x98\x01\n" +
	"\x0eAddEmployeeReq\x12\"\n" +
	"\femployeeName\x18\x01 \x01(\tR\femployeeName\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x120\n" +
	"\x04role\x18\x04 \x01(\x0e2\x1c.restaurant_rpc.EmployeeRoleR\x04role\"?\n" +
	"\x0fAddEmployeeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb7\x01\n" +
	"\x0fEmployeeService\x12T\n" +
	"\x0fGetEmployeeList\x12\x1f.restaurant_rpc.EmployeeListReq\x1a .restaurant_rpc.EmployeeListResp\x12N\n" +
	"\vAddEmployee\x12\x1e.restaurant_rpc.AddEmployeeReq\x1a\x1f.restaurant_rpc.AddEmployeeRespB'Z%restaurant_backend/rpc;restaurant_rpcb\x06proto3"

var (
	file_employee_service_proto_rawDescOnce sync.Once
	file_employee_service_proto_rawDescData []byte
)

func file_employee_service_proto_rawDescGZIP() []byte {
	file_employee_service_proto_rawDescOnce.Do(func() {
		file_employee_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_proto_rawDesc), len(file_employee_service_proto_rawDesc)))
	})
	return file_employee_service_proto_rawDescData
}

var file_employee_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_employee_service_proto_goTypes = []any{
	(*EmployeeListReq)(nil),  // 0: restaurant_rpc.EmployeeListReq
	(*EmployeeInfo)(nil),     // 1: restaurant_rpc.EmployeeInfo
	(*EmployeeListResp)(nil), // 2: restaurant_rpc.EmployeeListResp
	(*AddEmployeeReq)(nil),   // 3: restaurant_rpc.AddEmployeeReq
	(*AddEmployeeResp)(nil),  // 4: restaurant_rpc.AddEmployeeResp
	(*PageInfo)(nil),         // 5: restaurant_rpc.PageInfo
	(EmployeeRole)(0),        // 6: restaurant_rpc.EmployeeRole
}
var file_employee_service_proto_depIdxs = []int32{
	5, // 0: restaurant_rpc.EmployeeListReq.pageInfo:type_name -> restaurant_rpc.PageInfo
	6, // 1: restaurant_rpc.EmployeeInfo.role:type_name -> restaurant_rpc.EmployeeRole
	1, // 2: restaurant_rpc.EmployeeListResp.employeeList:type_name -> restaurant_rpc.EmployeeInfo
	5, // 3: restaurant_rpc.EmployeeListResp.pageInfo:type_name -> restaurant_rpc.PageInfo
	6, // 4: restaurant_rpc.AddEmployeeReq.role:type_name -> restaurant_rpc.EmployeeRole
	0, // 5: restaurant_rpc.EmployeeService.GetEmployeeList:input_type -> restaurant_rpc.EmployeeListReq
	3, // 6: restaurant_rpc.EmployeeService.AddEmployee:input_type -> restaurant_rpc.AddEmployeeReq
	2, // 7: restaurant_rpc.EmployeeService.GetEmployeeList:output_type -> restaurant_rpc.EmployeeListResp
	4, // 8: restaurant_rpc.EmployeeService.AddEmployee:output_type -> restaurant_rpc.AddEmployeeResp
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_employee_service_proto_init() }
func file_employee_service_proto_init() {
	if File_employee_service_proto != nil {
		return
	}
	file_basic_service_proto_init()
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_proto_rawDesc), len(file_employee_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employee_service_proto_goTypes,
		DependencyIndexes: file_employee_service_proto_depIdxs,
		MessageInfos:      file_employee_service_proto_msgTypes,
	}.Build()
	File_employee_service_proto = out.File
	file_employee_service_proto_goTypes = nil
	file_employee_service_proto_depIdxs = nil
}
