// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: types.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 桌子类型
type TableShape int32

const (
	TableShape_TABLE_TYPE_UNKNOWN TableShape = 0
	TableShape_TABLE_TYPE_SQUARE  TableShape = 1 // 方桌
	TableShape_TABLE_TYPE_RECT    TableShape = 2 // 长桌
)

// Enum value maps for TableShape.
var (
	TableShape_name = map[int32]string{
		0: "TABLE_TYPE_UNKNOWN",
		1: "TABLE_TYPE_SQUARE",
		2: "TABLE_TYPE_RECT",
	}
	TableShape_value = map[string]int32{
		"TABLE_TYPE_UNKNOWN": 0,
		"TABLE_TYPE_SQUARE":  1,
		"TABLE_TYPE_RECT":    2,
	}
)

func (x TableShape) Enum() *TableShape {
	p := new(TableShape)
	*p = x
	return p
}

func (x TableShape) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableShape) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (TableShape) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x TableShape) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableShape.Descriptor instead.
func (TableShape) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

type RoomType int32

const (
	RoomType_ROOM_TYPE_UNKNOWN RoomType = 0
	RoomType_ROOM_TYPE_ALL     RoomType = 1 // 必须全部包下
	RoomType_ROOM_TYPE_SHARE   RoomType = 2 // 可以只包该房间内的部分餐桌
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "ROOM_TYPE_UNKNOWN",
		1: "ROOM_TYPE_ALL",
		2: "ROOM_TYPE_SHARE",
	}
	RoomType_value = map[string]int32{
		"ROOM_TYPE_UNKNOWN": 0,
		"ROOM_TYPE_ALL":     1,
		"ROOM_TYPE_SHARE":   2,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[1].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[1]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

type SellStatus int32

const (
	SellStatus_SELL_STATUS_UNKNOWN  SellStatus = 0
	SellStatus_SELL_STATUS_SELLING  SellStatus = 1 // 在售
	SellStatus_SELL_STATUS_SOLD_OUT SellStatus = 2 // 售罄
	SellStatus_SELL_STATUS_REMOVE   SellStatus = 3 // 下架
)

// Enum value maps for SellStatus.
var (
	SellStatus_name = map[int32]string{
		0: "SELL_STATUS_UNKNOWN",
		1: "SELL_STATUS_SELLING",
		2: "SELL_STATUS_SOLD_OUT",
		3: "SELL_STATUS_REMOVE",
	}
	SellStatus_value = map[string]int32{
		"SELL_STATUS_UNKNOWN":  0,
		"SELL_STATUS_SELLING":  1,
		"SELL_STATUS_SOLD_OUT": 2,
		"SELL_STATUS_REMOVE":   3,
	}
)

func (x SellStatus) Enum() *SellStatus {
	p := new(SellStatus)
	*p = x
	return p
}

func (x SellStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SellStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[2].Descriptor()
}

func (SellStatus) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[2]
}

func (x SellStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SellStatus.Descriptor instead.
func (SellStatus) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

type DishPortion int32

const (
	DishPortion_DISH_PORTION_UNKNOWN DishPortion = 0
	DishPortion_DISH_PORTION_SMALL   DishPortion = 1 // 小份
	DishPortion_DISH_PORTION_MID     DishPortion = 2 // 中份
	DishPortion_DISH_PORTION_BIG     DishPortion = 3 // 大份
)

// Enum value maps for DishPortion.
var (
	DishPortion_name = map[int32]string{
		0: "DISH_PORTION_UNKNOWN",
		1: "DISH_PORTION_SMALL",
		2: "DISH_PORTION_MID",
		3: "DISH_PORTION_BIG",
	}
	DishPortion_value = map[string]int32{
		"DISH_PORTION_UNKNOWN": 0,
		"DISH_PORTION_SMALL":   1,
		"DISH_PORTION_MID":     2,
		"DISH_PORTION_BIG":     3,
	}
)

func (x DishPortion) Enum() *DishPortion {
	p := new(DishPortion)
	*p = x
	return p
}

func (x DishPortion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DishPortion) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[3].Descriptor()
}

func (DishPortion) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[3]
}

func (x DishPortion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DishPortion.Descriptor instead.
func (DishPortion) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

type UintType int32

const (
	UintType_UINT_TYPE_UNKNOWN UintType = 0
	UintType_UINT_TYPE_VOLUME  UintType = 1 // 体积, L
	UintType_UINT_TYPE_MASS    UintType = 2 // 质量, KG
	UintType_UINT_TYPE_PER     UintType = 3 // 份数, 整数
)

// Enum value maps for UintType.
var (
	UintType_name = map[int32]string{
		0: "UINT_TYPE_UNKNOWN",
		1: "UINT_TYPE_VOLUME",
		2: "UINT_TYPE_MASS",
		3: "UINT_TYPE_PER",
	}
	UintType_value = map[string]int32{
		"UINT_TYPE_UNKNOWN": 0,
		"UINT_TYPE_VOLUME":  1,
		"UINT_TYPE_MASS":    2,
		"UINT_TYPE_PER":     3,
	}
)

func (x UintType) Enum() *UintType {
	p := new(UintType)
	*p = x
	return p
}

func (x UintType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UintType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[4].Descriptor()
}

func (UintType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[4]
}

func (x UintType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UintType.Descriptor instead.
func (UintType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNKNOWN   OrderType = 0
	OrderType_ORDER_TYPE_DINING_IN OrderType = 1 // 堂食
	OrderType_ORDER_TYPE_TAKE_OUT  OrderType = 2 // 外卖
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNKNOWN",
		1: "ORDER_TYPE_DINING_IN",
		2: "ORDER_TYPE_TAKE_OUT",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNKNOWN":   0,
		"ORDER_TYPE_DINING_IN": 1,
		"ORDER_TYPE_TAKE_OUT":  2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[5].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[5]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

type CouponType int32

const (
	CouponType_COUPON_TYPE_UNKNOWN      CouponType = 0
	CouponType_COUPON_TYPE_FIXED_AMOUNT CouponType = 1 // 固定金额优惠
	CouponType_COUPON_TYPE_PERCENTAGE   CouponType = 2 // 百分比折扣
)

// Enum value maps for CouponType.
var (
	CouponType_name = map[int32]string{
		0: "COUPON_TYPE_UNKNOWN",
		1: "COUPON_TYPE_FIXED_AMOUNT",
		2: "COUPON_TYPE_PERCENTAGE",
	}
	CouponType_value = map[string]int32{
		"COUPON_TYPE_UNKNOWN":      0,
		"COUPON_TYPE_FIXED_AMOUNT": 1,
		"COUPON_TYPE_PERCENTAGE":   2,
	}
)

func (x CouponType) Enum() *CouponType {
	p := new(CouponType)
	*p = x
	return p
}

func (x CouponType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CouponType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[6].Descriptor()
}

func (CouponType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[6]
}

func (x CouponType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CouponType.Descriptor instead.
func (CouponType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

type CouponScope int32

const (
	CouponScope_COUPON_SCOPE_UNKNOWN     CouponScope = 0
	CouponScope_COUPON_SCOPE_ORDER_SCOPE CouponScope = 1 // 作用于整个订单
	CouponScope_COUPON_SCOPE_DISH_SCOPE  CouponScope = 2 // 作用于特定菜品
)

// Enum value maps for CouponScope.
var (
	CouponScope_name = map[int32]string{
		0: "COUPON_SCOPE_UNKNOWN",
		1: "COUPON_SCOPE_ORDER_SCOPE",
		2: "COUPON_SCOPE_DISH_SCOPE",
	}
	CouponScope_value = map[string]int32{
		"COUPON_SCOPE_UNKNOWN":     0,
		"COUPON_SCOPE_ORDER_SCOPE": 1,
		"COUPON_SCOPE_DISH_SCOPE":  2,
	}
)

func (x CouponScope) Enum() *CouponScope {
	p := new(CouponScope)
	*p = x
	return p
}

func (x CouponScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CouponScope) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[7].Descriptor()
}

func (CouponScope) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[7]
}

func (x CouponScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CouponScope.Descriptor instead.
func (CouponScope) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

type CouponTarget int32

const (
	CouponTarget_COUPON_TARGET_UNKNOWN        CouponTarget = 0
	CouponTarget_COUPON_TARGET_DISH_TARGET    CouponTarget = 1 // 针对菜品
	CouponTarget_COUPON_TARGET_PORTION_TARGET CouponTarget = 2 // 针对份量
)

// Enum value maps for CouponTarget.
var (
	CouponTarget_name = map[int32]string{
		0: "COUPON_TARGET_UNKNOWN",
		1: "COUPON_TARGET_DISH_TARGET",
		2: "COUPON_TARGET_PORTION_TARGET",
	}
	CouponTarget_value = map[string]int32{
		"COUPON_TARGET_UNKNOWN":        0,
		"COUPON_TARGET_DISH_TARGET":    1,
		"COUPON_TARGET_PORTION_TARGET": 2,
	}
)

func (x CouponTarget) Enum() *CouponTarget {
	p := new(CouponTarget)
	*p = x
	return p
}

func (x CouponTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CouponTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[8].Descriptor()
}

func (CouponTarget) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[8]
}

func (x CouponTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CouponTarget.Descriptor instead.
func (CouponTarget) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\n" +
	"restaurant*P\n" +
	"\n" +
	"TableShape\x12\x16\n" +
	"\x12TABLE_TYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11TABLE_TYPE_SQUARE\x10\x01\x12\x13\n" +
	"\x0fTABLE_TYPE_RECT\x10\x02*I\n" +
	"\bRoomType\x12\x15\n" +
	"\x11ROOM_TYPE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rROOM_TYPE_ALL\x10\x01\x12\x13\n" +
	"\x0fROOM_TYPE_SHARE\x10\x02*p\n" +
	"\n" +
	"SellStatus\x12\x17\n" +
	"\x13SELL_STATUS_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13SELL_STATUS_SELLING\x10\x01\x12\x18\n" +
	"\x14SELL_STATUS_SOLD_OUT\x10\x02\x12\x16\n" +
	"\x12SELL_STATUS_REMOVE\x10\x03*k\n" +
	"\vDishPortion\x12\x18\n" +
	"\x14DISH_PORTION_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12DISH_PORTION_SMALL\x10\x01\x12\x14\n" +
	"\x10DISH_PORTION_MID\x10\x02\x12\x14\n" +
	"\x10DISH_PORTION_BIG\x10\x03*^\n" +
	"\bUintType\x12\x15\n" +
	"\x11UINT_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10UINT_TYPE_VOLUME\x10\x01\x12\x12\n" +
	"\x0eUINT_TYPE_MASS\x10\x02\x12\x11\n" +
	"\rUINT_TYPE_PER\x10\x03*V\n" +
	"\tOrderType\x12\x16\n" +
	"\x12ORDER_TYPE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14ORDER_TYPE_DINING_IN\x10\x01\x12\x17\n" +
	"\x13ORDER_TYPE_TAKE_OUT\x10\x02*_\n" +
	"\n" +
	"CouponType\x12\x17\n" +
	"\x13COUPON_TYPE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18COUPON_TYPE_FIXED_AMOUNT\x10\x01\x12\x1a\n" +
	"\x16COUPON_TYPE_PERCENTAGE\x10\x02*b\n" +
	"\vCouponScope\x12\x18\n" +
	"\x14COUPON_SCOPE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18COUPON_SCOPE_ORDER_SCOPE\x10\x01\x12\x1b\n" +
	"\x17COUPON_SCOPE_DISH_SCOPE\x10\x02*j\n" +
	"\fCouponTarget\x12\x19\n" +
	"\x15COUPON_TARGET_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19COUPON_TARGET_DISH_TARGET\x10\x01\x12 \n" +
	"\x1cCOUPON_TARGET_PORTION_TARGET\x10\x02B\x05Z\x03pb/b\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_types_proto_goTypes = []any{
	(TableShape)(0),   // 0: restaurant.TableShape
	(RoomType)(0),     // 1: restaurant.RoomType
	(SellStatus)(0),   // 2: restaurant.SellStatus
	(DishPortion)(0),  // 3: restaurant.DishPortion
	(UintType)(0),     // 4: restaurant.UintType
	(OrderType)(0),    // 5: restaurant.OrderType
	(CouponType)(0),   // 6: restaurant.CouponType
	(CouponScope)(0),  // 7: restaurant.CouponScope
	(CouponTarget)(0), // 8: restaurant.CouponTarget
}
var file_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
